create table audit.project_audit (
    id bigint generated by default as identity primary key,
    project_ref uuid not null,
    actor_gotrue_id uuid,
    payload jsonb not null default '{}'::jsonb
);

alter table audit.project_audit
    add constraint project_audit_project_ref_fkey
    foreign key (project_ref)
    references app.projects(ref)
    on delete cascade;
