-- state B: the same column as identity; the grant on the (now identity-backed)
-- sequence must survive the serial → identity migration.
DO $$ BEGIN CREATE ROLE corpus_serial_ident_r NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE SCHEMA test_schema;
CREATE TABLE test_schema.t_ser (id int GENERATED BY DEFAULT AS IDENTITY, v int);
GRANT USAGE ON SEQUENCE test_schema.t_ser_id_seq TO corpus_serial_ident_r;
