name: Setup

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: pnpm
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      shell: bash
      run: pnpm install