create table app.organizations (
    id bigint generated by default as identity primary key,
    slug app.slug_text not null unique,
    billing_email text not null,
    inserted_at timestamp without time zone default timezone('utc', now()) not null
);
