create table app.project_events (
    id bigint generated by default as identity,
    project_id bigint not null references app.projects(id) on delete cascade,
    kind app.project_event_kind not null,
    payload jsonb not null default '{}'::jsonb,
    inserted_at timestamp without time zone default timezone('utc', now()) not null,
    primary key (id, kind)
) partition by list (kind);

create table app.project_events_default partition of app.project_events default;

create index idx_project_events_kind on only app.project_events using btree (kind);
create index project_events_default_kind_idx on app.project_events_default using btree (kind);

alter index app.idx_project_events_kind
    attach partition app.project_events_default_kind_idx;
