import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const currentDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(currentDir, "..");
const packageJsonPath = join(packageRoot, "package.json");
const versionModulePath = join(packageRoot, "src", "cli", "version.ts");

const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8")) as {
  readonly version: string;
};

const nextContent = `// Generated by scripts/sync-cli-version.ts

export const PGDELTA_CLI_VERSION = "${packageJson.version}";
`;

const currentContent = (() => {
  try {
    return readFileSync(versionModulePath, "utf8");
  } catch {
    return undefined;
  }
})();

if (currentContent !== nextContent) {
  writeFileSync(versionModulePath, nextContent);
}
