import type { TableDefinition } from "../types.ts";

export function serializeTableCreate(table: TableDefinition): string {
  const columns = table.columns
    .map((column) => {
      const parts: string[] = [];

      // name and type
      parts.push(`${column.name} ${column.type}`);

      // nullable
      if (!column.nullable) {
        parts.push("not null");
      }

      // identity
      if (column.identity === "a") {
        parts.push("generated always as identity");
      } else if (column.identity === "d") {
        parts.push("generated by default as identity");
      }

      // generated
      if (column.generated === "a") {
        parts.push("generated always as");
      } else if (column.generated === "s") {
        parts.push("generated stored as");
      }

      // default
      if (column.default !== null) {
        parts.push(`default ${column.default}`);
      }

      return parts.join(" ");
    })
    .join(",\n  ");

  const options = table.table_options
    ? `\nwith (${table.table_options.join(", ")})`
    : "";

  return `create table ${table.schema_name}.${table.table_name} (\n  ${columns}\n)${options};`;
}
