/**
 * Supabase policy package: filtering rules for Supabase-managed PostgreSQL
 * databases (target-architecture §3.9, stage-08-policy).
 *
 * Port of packages/pg-delta/src/core/integrations/supabase.ts into DSL v2.
 * v2 semantics: rules evaluated in order, first match wins, no match → include.
 * Rule ordering: specific INCLUDE rules first, then EXCLUDE rules.
 *
 * OLD RULE → NEW RULE MAPPING (for audit completeness)
 *
 * Old-1: objectType extension + operation create
 *        → { kind:"extension", verb:"add" } → include
 *
 * Old-2: objectType extension + operation drop
 *        → { kind:"extension", verb:"remove" } → include
 *
 * Old-3: objectType trigger AND trigger-schema IN SYSTEM
 *        AND NOT trigger-function_schema IN SYSTEM
 *        AND NOT (schema=pgmq AND table matches q_/a_ prefix)
 *        → { kind:"trigger", schema IN SYSTEM, not edgeTo{kind:"function", schema IN SYSTEM},
 *            not (schema=pgmq AND table glob q_* or a_*) } → include
 *
 * Old-4: "star-slash-schema" IN SUPABASE_SYSTEM_SCHEMAS
 *        → { schema: SUPABASE_SYSTEM_SCHEMAS } → exclude
 *
 * Old-5: "schema/name" IN SUPABASE_SYSTEM_SCHEMAS
 *        → { kind:"schema", name: SUPABASE_SYSTEM_SCHEMAS } → exclude
 *
 * Old-6: "star-slash-owner" IN SUPABASE_SYSTEM_ROLES
 *        → { owner: SUPABASE_SYSTEM_ROLES } → exclude
 *
 * Old-7: "role/name" IN SUPABASE_SYSTEM_ROLES
 *        → { kind:"role", name: SUPABASE_SYSTEM_ROLES } → exclude
 *
 * Old-8: membership where member OR role is a system role
 *        → { kind:"membership", idField{field:"member"} IN SYSTEM_ROLES } → exclude
 *           { kind:"membership", idField{field:"role"} IN SYSTEM_ROLES } → exclude
 *
 * Old-9: objectType foreign_data_wrapper + scope privilege
 *        → { kind:"acl", target:{kind:"fdw"} } → exclude
 *        (GRANT/REVOKE on FDW requires superuser; non-superuser postgres
 *        cannot replay this ACL regardless of FDW ownership)
 *
 * Old-10: implicitly filtered in old engine via parent-object exclusion
 *         → { kind:["acl","comment","securityLabel"], target:{schema IN SYSTEM} } → exclude
 *            { kind:["acl","comment","securityLabel"], target:{kind:"schema", name IN SYSTEM_SCHEMAS} } → exclude
 *         Two sub-rules under the unified target predicate: target.schema covers
 *         qualified-kind targets (table, view, sequence...) while target.kind+name
 *         covers simple-kind targets like schema itself (in v2, satellite deltas
 *         are independent; must be excluded explicitly)
 *
 * Old-11: emptyCatalog: undefined (TODO in old engine)
 *         → baseline: "supabase-baseline"
 *         (snapshot generated by scripts/generate-supabase-baseline.ts)
 *
 * Old-12: Wasm FDW filtering via wasm_fdw_handler/validator function names
 *         → replaced structurally (CLI-1470): extraction-time pg_depend 'e'
 *         rows exclude extension-member FDWs at extract time, and Rule 6c
 *         excludes user-kind FDWs whose handler/validator come from the
 *         `wrappers` extension ({ kind:"fdw", edgeTo depends
 *         extension:wrappers }) — those are dashboard-provisioned and owned
 *         by `postgres` on Cloud, so neither the extract-time guard nor the
 *         owner predicate catches them.
 *
 * Old-13: serialize skipAuthorization for schema CREATE owned by system role
 *         → serialize rule: { kind: schema, owner: SYSTEM_ROLES } sets
 *         skipAuthorization — the planner applies serialize params PER
 *         MATCHED FACT (first-match-wins), so user schemas keep their
 *         AUTHORIZATION clause
 *
 * Old-14: serialize skipSchema for extensions installing their own schema
 *         → REMOVED. The SCHEMA clause is now derived from the extension's
 *         `relocatable` fact (pg_extension.extrelocatable): a non-relocatable
 *         extension emits a bare CREATE EXTENSION. No name list, not
 *         Supabase-specific. See docs/architecture/managed-view-architecture.md (move 2).
 *
 * BASELINE
 * The baseline field names the snapshot that represents "empty" on a Supabase
 * platform instance. Facts present-and-identical in the baseline are subtracted
 * before diffing (via subtractBaseline), replacing the old emptyCatalog TODO.
 * Regenerate: bun run scripts/generate-supabase-baseline.ts <db-url> <pg-major>
 */

import type { Policy } from "./policy.ts";

// ---------------------------------------------------------------------------
// Lists copied VERBATIM from packages/pg-delta/src/core/integrations/supabase.ts
// ---------------------------------------------------------------------------

/** Supabase system schemas that should be excluded from user plans. */
export const SUPABASE_SYSTEM_SCHEMAS = [
  "_analytics",
  "_realtime",
  "_supavisor",
  "auth",
  "cron",
  "etl",
  "extensions",
  "graphql",
  "graphql_public",
  "information_schema",
  "net",
  "pgbouncer",
  "pgmq",
  "pgmq_public",
  "pgsodium",
  "pgsodium_masks",
  "pgtle",
  "realtime",
  "storage",
  "supabase_functions",
  "supabase_migrations",
  "vault",
] as const;

/** Supabase system roles that should be excluded from user plans. */
export const SUPABASE_SYSTEM_ROLES = [
  "anon",
  "authenticated",
  "authenticator",
  "cli_login_postgres",
  "dashboard_user",
  "pgbouncer",
  "pgsodium_keyholder",
  "pgsodium_keyiduser",
  "pgsodium_keymaker",
  "pgtle_admin",
  "service_role",
  "supabase_admin",
  "supabase_auth_admin",
  "supabase_etl_admin",
  "supabase_functions_admin",
  "supabase_privileged_role",
  "supabase_read_only_user",
  "supabase_realtime_admin",
  "supabase_replication_admin",
  "supabase_storage_admin",
  "supabase_superuser",
] as const;

/** Supabase platform-managed extensions: enabled by the platform image, never
 *  declared in a user's `schemas/` files, so a declarative diff must neither
 *  create nor drop them — the reported spurious `DROP EXTENSION pg_graphql`
 *  (supabase/cli#5555). Deliberately conservative: user-toggleable extensions
 *  (pg_net, pg_cron, pgmq, pgcrypto, uuid-ossp, …) are intentionally absent so
 *  users can still manage them. The comprehensive mechanism is the committed
 *  Supabase baseline (a v1 gate — see the `baseline` note below); this name
 *  list mirrors SUPABASE_SYSTEM_SCHEMAS/ROLES until that lands. */
export const SUPABASE_SYSTEM_EXTENSIONS = [
  "pg_graphql",
  "pg_stat_statements",
  "pgsodium",
  "supabase_vault",
  // Installed by the dashboard when the user enables a wrapper integration,
  // never declared in user schema files — same judgment as pg_graphql. Also
  // load-bearing for Rule 6c below (CLI-1470): with wrappers-provisioned FDWs
  // projected out, a managed `DROP EXTENSION "wrappers"` would be a bare drop
  // PostgreSQL rejects (the suppressed FDW still depends on the extension's
  // handler/validator), so the extension and its FDWs are platform-managed
  // together.
  "wrappers",
] as const;

/** Supabase platform-created publications: provisioned at project init (by the
 *  Realtime service / CLI init scripts, so they are NOT in the base image and a
 *  future committed baseline would not cover them) and typically owned by
 *  `postgres`, so no owner/schema rule catches them. The publication OBJECT is
 *  never the user's to create or drop, but `supabase_realtime` MEMBERSHIP is
 *  user-managed state (`ALTER PUBLICATION supabase_realtime ADD TABLE …` is the
 *  documented way to enable Realtime on a table) — hence the exclude rule below
 *  plus the `assumedPublications` reference-only carve-out (#370).
 *  `supabase_realtime_messages_publication` (Realtime broadcast-from-database,
 *  publishing `realtime.messages`) has no user-managed membership — its members
 *  live in the `realtime` system schema — so it is excluded here but NOT
 *  assumed: it hard-prunes with its members. */
const SUPABASE_SYSTEM_PUBLICATIONS = [
  "supabase_realtime",
  "supabase_realtime_messages_publication",
] as const;

/** Managed-schema tables whose RLS policies are user intent, not platform state.
 *  The platform seeds none on these surfaces (pinned by the full-stack fixture
 *  in `tests/supabase-base-init.test.ts` and by the pristine guard in
 *  `tests/supabase-managed-policies.test.ts` after `applySupabaseBaseInit`);
 *  any policy present is user-authored. Policies have no owner — do not
 *  inspect `usingExpr`.
 *
 *  Source of truth: the platform's `supautils.policy_grants` GUC — the tables
 *  the non-superuser `postgres` role is ALLOWED to run CREATE/ALTER/DROP
 *  POLICY on (supabase/postgres,
 *  ansible/files/postgresql_config/supautils.conf.j2). Deliberate deltas from
 *  that list:
 *    - `auth.*` (16 tables in the grant): covered SCHEMA-WIDE via
 *      SUPABASE_USER_POLICY_SCHEMAS below, not listed here.
 *    - `storage.prefixes`: grantable, but absent from the pinned base-init
 *      fixture (the pristine guard cannot vouch for it yet); add it with the
 *      next Supabase image sync (`bun run sync-base-images`). */
export const SUPABASE_USER_POLICY_SURFACES = [
  { schema: "storage", table: "objects" },
  { schema: "storage", table: "buckets" },
  { schema: "storage", table: "buckets_analytics" },
  { schema: "storage", table: "s3_multipart_uploads" },
  { schema: "storage", table: "s3_multipart_uploads_parts" },
  { schema: "realtime", table: "messages" },
  { schema: "realtime", table: "subscription" },
] as const;

/** Managed schemas where EVERY RLS policy is user intent, whatever its table.
 *
 *  `auth` (Auth team, 2026-08-29): the service never ships or manages RLS
 *  policies on its own tables — all policies there are user-managed. That
 *  forward-looking guarantee is the invariant this rule rests on (policies
 *  carry no owner, so one seeded policy would break the discriminator); the
 *  pristine guard in `tests/supabase-managed-policies.test.ts` and the
 *  fixture pin in `tests/supabase-base-init.test.ts` pin the observable half
 *  (zero policies on auth in the base init).
 *
 *  Schema-wide rather than mirroring the supautils policy_grants table list
 *  because the guarantee is schema-scoped: it round-trips the
 *  legal-but-inert case (`auth.oauth_clients` is grantable but RLS is never
 *  enabled) and is immune to grant-list drift (the post-2024 tables such as
 *  `auth.passkeys` intentionally have no grant today — the Auth team
 *  confirmed the drift is deliberate). auth never runs FORCE ROW LEVEL
 *  SECURITY and `supabase_auth_admin` owns its tables, so a customer policy
 *  cannot alter Auth's own runtime behavior; the one sharp edge is a policy
 *  referencing a column that a service migration later rewrites (documented
 *  "at your own risk" — backup-restore.mdx tells users these policies must
 *  be restored, which is exactly what this rule makes pg-delta do).
 *
 *  storage / realtime stay on the per-table SURFACES list above until their
 *  teams give the same forward-looking guarantee. */
export const SUPABASE_USER_POLICY_SCHEMAS = ["auth"] as const;

// ---------------------------------------------------------------------------
// The Supabase policy
// ---------------------------------------------------------------------------

/**
 * The Supabase policy: port of every filterable behavior from the old
 * supabase.ts into DSL v2.
 */
export const supabasePolicy: Policy = {
  id: "supabase",

  // Platform-preset roles assumed to exist at apply time. Rule 7 below projects
  // their role OBJECT out of the managed view, but ACL / default-privilege facts
  // that grant TO them are kept — old pg-delta emits those grants and dbdev
  // relies on them. Declaring the names here lets the planner's ambient-role
  // exemption (like pg_*/PUBLIC) accept `consumes role:anon` without re-admitting
  // the role into the diff. Mirrors Rule 7's exclusion list by construction,
  // plus `postgres` (Rule 7b projects its role OBJECT out too, and every kept
  // user object references it as owner/grantee).
  assumedRoles: [...SUPABASE_SYSTEM_ROLES, "postgres"],

  // Platform-created publications assumed to exist at apply time. The
  // system-publication exclude rule below projects the publication OBJECT out
  // of the managed view, but naming it here downgrades that exclusion to
  // REFERENCE-ONLY (resolveView), so the user's `publicationRel` membership
  // facts survive and diff at rel grain: export emits `ALTER PUBLICATION
  // supabase_realtime ADD TABLE …` instead of rewriting the platform state as
  // CREATE PUBLICATION, apply never drops the platform publication, and the
  // co-located shadow seed materializes it so membership-only declarative
  // files load (#370). `supabase_realtime_messages_publication` is
  // deliberately absent — no user-managed membership, so it hard-prunes.
  assumedPublications: ["supabase_realtime"],

  // Platform-managed schemas assumed to exist at apply time. Rules 4/5 below
  // project their schema OBJECT out of the managed view, but a kept user object
  // can still reference one as a dependency target — most notably a relocatable
  // extension installed into `extensions` (`CREATE EXTENSION … SCHEMA
  // extensions`), which old pg-delta and dbdev rely on. Declaring the names here
  // lets the planner's ambient-schema exemption (like assumed roles / pg_* /
  // PUBLIC) accept `consumes schema:extensions` without re-admitting the schema
  // into the diff. Mirrors the system-schema exclusion list by construction.
  assumedSchemas: [...SUPABASE_SYSTEM_SCHEMAS],

  // Default owner for database-scope exports: Supabase hands users the
  // `postgres` role, so an object owned by `postgres` needs no `ALTER … OWNER
  // TO` — its ownership is implicit. Objects owned by a system role are already
  // projected out by Rule 6 (owner: SUPABASE_SYSTEM_ROLES), so this suppresses
  // only redundant `owner to postgres` lines; a user object owned by a
  // non-postgres user role still serializes its owner.
  defaultOwner: "postgres",

  // baseline (intentionally UNSET in v1): a baseline names the snapshot that
  // represents "empty" on a Supabase instance; facts present-and-identical in
  // it are subtracted before diffing (resolveBaseline → plan options.baseline),
  // so platform-managed objects are invisible without a filter rule per object.
  // No Supabase baseline snapshot is committed — DELIBERATELY (decision +
  // rationale + the prove-side wiring it still needs:
  // docs/roadmap/backlog.md "Supabase baseline snapshot"), so this policy does
  // NOT declare one — a declared-but-unresolved baseline fail-fasts (review
  // finding 3) rather than being silently ignored. The `filter` rules below are
  // the mechanism for hiding platform objects; when the baseline snapshot
  // lands, re-add `baseline: "supabase-baseline"` here and resolveBaseline will
  // subtract it. Generate with:
  //   bun run scripts/generate-supabase-baseline.ts <db-url> <pg-major>
  //
  // ⚠️ Phase 2b (#41) depends on this being UNSET: the co-located-shadow seed
  // (frontends/seed-assumed-schemas.ts) materializes assumed-schema objects from
  // the target's `resolveView` reference-only set, and subtractBaseline removes
  // baseline-identical facts BEFORE that marking — so a declared baseline empties
  // the seed and quick-mode `schema apply` regresses. When landing the baseline,
  // revisit the seed derivation; the "non-empty seed" pin in
  // seed-assumed-schemas.test.ts fails loudly if this is missed.

  serialize: [
    // Old-13 (REMOVED): the skipAuthorization serialize rule is no longer needed.
    // With owner-as-edge (move 2), when a schema is owned by a system role that
    // is excluded from the view, the owner edge is pruned by buildFactBase before
    // diffing — so no owner edge exists → no ALTER SCHEMA … OWNER TO is emitted
    // → CREATE SCHEMA renders without AUTHORIZATION by construction, not via param.
    // See docs/architecture/managed-view-architecture.md (move 2).
    //
    // Old-14 (REMOVED): the SCHEMA clause is now derived from the extension's
    // `relocatable` fact (pg_extension.extrelocatable) in the extension rule —
    // a non-relocatable extension (pgmq / pgsodium / pgtle) emits a bare
    // CREATE EXTENSION with no name list and nothing Supabase-specific.
    // See docs/architecture/managed-view-architecture.md (move 2).
  ],

  filter: [
    // -------------------------------------------------------------------------
    // INCLUDE rules (specific cases that must survive system-level exclusions)
    // Must appear BEFORE the exclude rules (first-match-wins).
    // -------------------------------------------------------------------------

    // Exclude platform-managed extensions (pg_graphql, …) entirely: they are
    // enabled by the Supabase image, never declared in user schema files, and
    // must not be dropped when absent from the declarative source — the
    // reported `DROP EXTENSION pg_graphql` (supabase/cli#5555). MUST precede the
    // general extension include below (first-match-wins) so it wins for these
    // names; all OTHER extensions still fall through to the include and stay
    // user-declarable. No `verb` clause → also suppresses spurious version
    // (`set`) churn on a platform extension. The robust long-term mechanism is
    // the committed Supabase baseline (the `baseline` note below).
    {
      match: {
        all: [{ kind: "extension" }, { name: [...SUPABASE_SYSTEM_EXTENSIONS] }],
      },
      action: "exclude",
    },

    // Exclude platform-created publications (see SUPABASE_SYSTEM_PUBLICATIONS):
    // provisioned at project init and typically owned by `postgres`, so neither
    // the schema nor the owner rules below catch them. Reported as #370: export
    // rewrote `supabase_realtime` as CREATE PUBLICATION and apply planned
    // DROP PUBLICATION when user files (correctly) omitted it. The name predicate
    // matches only `publication` facts — membership facts (`publicationRel` /
    // `publicationSchema`) carry no `name` field, so they stay managed; for
    // `supabase_realtime` the `assumedPublications` entry above turns this
    // exclusion reference-only so those membership facts keep their parent.
    {
      match: {
        all: [
          { kind: "publication" },
          { name: [...SUPABASE_SYSTEM_PUBLICATIONS] },
        ],
      },
      action: "exclude",
      audit: {
        reasonCode: "supabase.system-publication",
        classification: "acknowledged",
      },
    },

    // Exclude comment / security-label satellites TARGETING a platform
    // publication (mirrors Rule 10, which does the same for system-schema
    // objects). The reference-only mark above covers only the publication fact
    // itself; a satellite is a managed CHILD of that reference-only parent, so
    // without this rule a platform-set comment absent from user files would
    // plan `COMMENT ON PUBLICATION supabase_realtime IS NULL` — mutating
    // platform metadata the user never declared. Membership facts
    // (publicationRel / publicationSchema) are NOT satellites and stay managed.
    // (Publications carry no ACLs, so acl is not matched here.)
    {
      match: {
        all: [
          { kind: ["comment", "securityLabel"] },
          {
            target: {
              kind: "publication",
              name: [...SUPABASE_SYSTEM_PUBLICATIONS],
            },
          },
        ],
      },
      action: "exclude",
      audit: {
        reasonCode: "supabase.system-publication-satellite",
        classification: "acknowledged",
      },
    },

    // Rule 1+2 (old rules): include extension CREATE and DROP operations.
    // Extensions are always user-declarable state on Supabase regardless of
    // the schema they install into. Place before the system-schema/owner
    // exclusions so e.g. `CREATE EXTENSION pgmq` (schema=pgmq) is not filtered.
    {
      match: { all: [{ kind: "extension" }, { verb: ["add", "remove"] }] },
      action: "include",
    },

    // Rule 3 (old rule): include user-created triggers on tables in managed
    // schemas. A trigger lives in the schema of the table it fires on, so a
    // customer trigger on `auth.users` appears in the `auth` schema and would
    // otherwise be caught by the system-schema exclusion below.
    //
    // The discriminator is the trigger function's schema: Supabase's own
    // triggers call functions inside the same managed schema, while a user
    // trigger points to a function in `public` (or another non-managed schema).
    //
    // Defensive exclusion: pgmq dynamically creates `pgmq.q_<name>` /
    // `pgmq.a_<name>` tables via `pgmq.create()` rather than
    // `CREATE EXTENSION pgmq`, so the extraction-time pg_depend 'e' guard may
    // miss them. Exclude triggers on those tables explicitly.
    {
      match: {
        all: [
          { kind: "trigger" },
          // trigger is on a table in a managed schema
          { schema: [...SUPABASE_SYSTEM_SCHEMAS] },
          // trigger function lives outside the managed schemas (user-owned)
          {
            not: {
              edgeTo: {
                kind: "function",
                schema: [...SUPABASE_SYSTEM_SCHEMAS],
              },
            },
          },
          // not a trigger on a pgmq queue / archive table
          {
            not: {
              all: [
                { schema: "pgmq" },
                {
                  any: [
                    { idField: { field: "table", glob: "q_*" } },
                    { idField: { field: "table", glob: "a_*" } },
                  ],
                },
              ],
            },
          },
        ],
      },
      action: "include",
    },

    // User RLS on managed-schema tables: an explicit per-table allowlist for
    // storage/realtime, plus the schema-wide SUPABASE_USER_POLICY_SCHEMAS
    // (auth — see the constant's doc for the Auth-team guarantee). Policies
    // have no owner, so the discriminator is the surface, not provenance.
    // MUST precede Rule 4 (first-match-wins): a policy's id.schema is the
    // table schema, so Rule 4 would otherwise exclude it. Because that
    // schema is also assumed, the exclusion is reference-only — the policy
    // stays in the view but never diffs or exports. Rule 10 does not match
    // kind:"policy" (satellites only); placement vs Rule 10 is not the game.
    {
      match: {
        all: [
          { kind: "policy" },
          {
            any: [
              ...SUPABASE_USER_POLICY_SURFACES.map((s) => ({
                all: [
                  { schema: s.schema },
                  { idField: { field: "table", glob: s.table } },
                ],
              })),
              ...SUPABASE_USER_POLICY_SCHEMAS.map((s) => ({ schema: s })),
            ],
          },
        ],
      },
      action: "include",
      audit: {
        reasonCode: "supabase.user-policy-surface",
        classification: "acknowledged",
      },
    },

    // Comments ON those user policies are user intent too (REAL-997: realtime
    // users document their policies with COMMENT ON POLICY). The policy fact
    // is managed by the rule above, but its comment SATELLITE would still be
    // excluded by Rule 10 (target.schema in SYSTEM_SCHEMAS) — dropped from
    // exports (a fork loses the comment) and, for a declarative consumer,
    // planned as `COMMENT ON POLICY … IS NULL`. Scoped per-surface via the
    // target.table sub-field: a comment on a platform policy elsewhere in the
    // schema, or on the surface TABLE itself, stays excluded. securityLabel /
    // acl are not matched — PostgreSQL supports neither on policies.
    {
      match: {
        all: [
          { kind: "comment" },
          {
            any: [
              ...SUPABASE_USER_POLICY_SURFACES.map((s) => ({
                target: { kind: "policy", schema: s.schema, table: s.table },
              })),
              ...SUPABASE_USER_POLICY_SCHEMAS.map((s) => ({
                target: { kind: "policy", schema: s },
              })),
            ],
          },
        ],
      },
      action: "include",
      audit: {
        reasonCode: "supabase.user-policy-surface-comment",
        classification: "acknowledged",
      },
    },

    // -------------------------------------------------------------------------
    // EXCLUDE rules — system objects the user cannot / should not manage
    // -------------------------------------------------------------------------

    // Rule 4 (old rule): exclude any fact whose identity schema is a system schema.
    // Covers: table, view, materializedView, foreignTable, sequence, index,
    // collation, domain, type, column, constraint, trigger, rule, policy,
    // procedure, aggregate — every qualified-kind or sub-entity kind.
    {
      match: { schema: [...SUPABASE_SYSTEM_SCHEMAS] },
      action: "exclude",
    },

    // Rule 5 (old rule): exclude schema objects whose OWN name is a system schema.
    // The `schema` predicate checks `fact.id.schema`, not `fact.id.name`, so
    // a `{ kind: "schema", name: "auth" }` fact has no `schema` field.
    // This rule closes that gap.
    {
      match: {
        all: [{ kind: "schema" }, { name: [...SUPABASE_SYSTEM_SCHEMAS] }],
      },
      action: "exclude",
    },

    // Platform event triggers (`issue_*` / `pgrst_*` / `graphql_watch_*`).
    // Identity, not owner: Rule 6 hides a supabase_admin-owned copy and keeps
    // a postgres-owned copy, so a same-named trigger becomes a false CREATE
    // (CLI-2341). Hard-exclude — nothing user-managed hangs off these, unlike
    // assumedPublications.
    {
      match: {
        all: [
          { kind: "eventTrigger" },
          { name: ["issue_*", "pgrst_*", "graphql_watch_*"] },
        ],
      },
      action: "exclude",
      audit: {
        reasonCode: "supabase.platform-event-trigger",
        classification: "acknowledged",
      },
    },

    // Rule 6 (old rule): exclude objects whose payload owner is a system role.
    // Covers tables, views, schemas, sequences, etc. that are managed by
    // Supabase system roles.
    //
    // `public` is the user schema even when a PG14-era catalog still lists
    // `supabase_admin` (bootstrap) as nspowner. Excluding it would DROP SCHEMA
    // public on a branch whose public is owned by pg_database_owner. Include
    // first-match so Rule 6 still hides system-owned *contents* of public.
    {
      match: { all: [{ kind: "schema" }, { name: "public" }] },
      action: "include",
    },
    {
      match: { owner: [...SUPABASE_SYSTEM_ROLES] },
      action: "exclude",
    },

    // Rule 6b (this session): exclude default-privilege entries DECLARED FOR a
    // system role (`ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin …`). Same
    // provenance judgment as Rule 6, but ADP facts carry no owner edge/payload —
    // the FOR-role is in the id (`id.role`). A non-superuser `postgres` can never
    // execute an ADP for a reserved system role, so these are platform-managed,
    // never the user's to manage. (Grantee-side, e.g. FOR ROLE postgres GRANT …
    // TO anon, is intentionally NOT matched — that is the user-owned API-role
    // default.)
    {
      match: {
        all: [
          { kind: "defaultPrivilege" },
          { idField: { field: "role", glob: [...SUPABASE_SYSTEM_ROLES] } },
        ],
      },
      action: "exclude",
    },

    // Rule 6c (CLI-1470): exclude FDWs provisioned through the Supabase
    // Wrappers product — the wrapper's handler/validator are members of the
    // `wrappers` extension, so pg_depend endpoint resolution collapses the
    // FDW's function dependencies onto the extension fact and the FDW carries
    // a `depends` edge to `extension:wrappers`. The owner rule (Rule 6) does
    // NOT cover these: on Cloud the dashboard runs CREATE FOREIGN DATA
    // WRAPPER as the privileged role via supautils, which switches to the
    // real superuser to execute it and then reassigns ownership back — so
    // `fdwowner = postgres`, not `supabase_admin` (verified empirically on a
    // live project, 2026-08-10). These wrappers are dashboard-managed
    // integrations, assumed present on both sides like managed roles and
    // platform extensions; their servers / foreign tables / user mappings
    // cascade out via the managed-view descendant pruning. A user FDW whose
    // handler is a hand-rolled function (or comes from any other extension,
    // e.g. a custom wrapper over postgres_fdw's handler) keeps round-tripping.
    // NOTE: this depends on the `wrappers` extension fact surviving into the
    // scope-evaluation view — true today (no Supabase baseline is committed,
    // and `wrappers` is dashboard-installed, not part of a fresh project); if
    // a committed baseline ever includes `wrappers`, subtractBaseline prunes
    // the edge's endpoint and this rule must be revisited (baseline.ts keeps
    // only edges whose both endpoints survive).
    {
      match: {
        all: [
          { kind: "fdw" },
          {
            edgeTo: {
              edgeKind: "depends",
              kind: "extension",
              name: "wrappers",
            },
          },
        ],
      },
      action: "exclude",
      audit: {
        reasonCode: "supabase.wrappers-fdw",
        classification: "acknowledged",
      },
    },

    // Rule 7 (old rule): exclude role objects whose name is a system role.
    // The `owner` predicate reads payload["owner"], not the role's own name.
    {
      match: {
        all: [{ kind: "role" }, { name: [...SUPABASE_SYSTEM_ROLES] }],
      },
      action: "exclude",
    },

    // Rule 7b (#371): exclude the `postgres` role OBJECT — but nothing else
    // about `postgres`. Supabase hands users a privileged NON-superuser
    // `postgres` whose role-level state is platform plumbing, not user-declared
    // desired state: the attribute flags can never be re-applied by the user
    // (supautils: "Only superusers can alter privileged roles") and the
    // `search_path` config is set by the image's own migrations. `postgres` is
    // deliberately NOT in SUPABASE_SYSTEM_ROLES — Rule 6 excludes objects OWNED
    // by listed roles, and `postgres` owns every user object, so listing it
    // would empty the export. Memberships where `postgres` is merely the MEMBER
    // of a user role (`GRANT app_admin TO postgres`) are legitimate user state
    // and stay managed. `assumedRoles` above includes `postgres` so kept
    // references (ownership, grants) still resolve at plan time. Trade-off,
    // accepted: user-customized role config ON `postgres` (e.g. a bespoke
    // `search_path`) no longer round-trips under cluster scope; the committed
    // Supabase baseline (post-v1, docs/roadmap/backlog.md) is the mechanism
    // that can distinguish platform-shipped from user-customized role state.
    {
      match: {
        all: [{ kind: "role" }, { name: "postgres" }],
      },
      action: "exclude",
      audit: {
        reasonCode: "supabase.platform-postgres-role",
        classification: "acknowledged",
      },
    },

    // Rule 8a (old rule): exclude memberships where the MEMBER is a system role.
    {
      match: {
        all: [
          { kind: "membership" },
          { idField: { field: "member", glob: [...SUPABASE_SYSTEM_ROLES] } },
        ],
      },
      action: "exclude",
    },

    // Rule 8b (old rule): exclude memberships where the ROLE (grantee) is a system role.
    {
      match: {
        all: [
          { kind: "membership" },
          { idField: { field: "role", glob: [...SUPABASE_SYSTEM_ROLES] } },
        ],
      },
      action: "exclude",
    },

    // Rule 9 (old rule): exclude ACL facts on FDWs.
    //
    // GRANT/REVOKE on FOREIGN DATA WRAPPER requires superuser (verified:
    // tests/capability.test.ts "a non-superuser cannot GRANT on a FOREIGN DATA
    // WRAPPER"). On Supabase Cloud `postgres` has the elevated rights, but the
    // local Docker image does not, so `supabase db reset` aborts with
    // "permission denied for foreign-data wrapper". The owner rule above
    // already covers wrappers owned by `supabase_admin`, but pg_dump rewrites
    // OWNER TO to whoever ran the dump, so after a restore the FDW often ends
    // up owned by `postgres` and slips past the owner gate. Since a
    // non-superuser `postgres` cannot grant on any FDW regardless of ownership,
    // the ACL diff is not user-replayable. We do NOT apply the same blanket
    // rule to FOREIGN SERVER: server GRANT/REVOKE does not require superuser
    // and user-created servers carry legitimate user ACL that must roundtrip.
    //
    // RETAINED, not retired (follow-up 2). The applier-capability mechanism
    // (move 6, capabilityExcludedRoots) now derives this exclusion precisely:
    // it drops FDW ACLs whenever the applier is non-superuser. The two are at
    // parity for the real Supabase flow (local + Cloud `postgres` are both
    // non-superuser). They DIVERGE for a superuser applier — capability would
    // (correctly) MANAGE the FDW ACL, while this rule excludes unconditionally.
    // This rule is kept because it is a SELF-CONTAINED policy guarantee: the
    // exclusion holds even if a caller forgets to probe + pass capability,
    // whereas capability depends on every caller supplying it. Capability is
    // the general mechanism (any non-superuser applier, any policy); this rule
    // is the Supabase policy's unconditional belt-and-suspenders. See
    // docs/architecture/managed-view-architecture.md (follow-up 2).
    {
      match: {
        all: [{ kind: "acl" }, { target: { kind: "fdw" } }],
      },
      action: "exclude",
      audit: {
        reasonCode: "supabase.fdw-acl",
        classification: "acknowledged",
      },
    },

    // Rule 10 (implicit in old engine): exclude ACL, comment, and security-label
    // satellite facts whose TARGET object lives in a system schema.
    //
    // In the old engine, satellite facts for system-schema objects were filtered
    // implicitly because the parent object was excluded first and satellites
    // cascaded. In v2, each delta is evaluated independently against the full
    // fact base, so we must explicitly exclude satellites targeting system objects.
    //
    // Two sub-rules under the unified `target` predicate:
    //   - target.schema covers qualified-kind targets (table, view, sequence, ...)
    //     which carry a `schema` field in their StableId.
    //   - target.kind + target.name covers simple-kind targets like schema
    //     which carry only a `name` field (no `schema`). We match schema-kind
    //     targets whose `name` is in SUPABASE_SYSTEM_SCHEMAS (covers ACLs on
    //     the auth schema itself, not just tables inside auth).
    //
    // Carve-out: comments ON user policies on SUPABASE_USER_POLICY_SURFACES
    // and SUPABASE_USER_POLICY_SCHEMAS are user intent and are kept managed
    // by the include rule above (first-match-wins), mirroring the
    // policy-surface include vs Rule 4.
    {
      match: {
        all: [
          { kind: ["acl", "comment", "securityLabel"] },
          {
            any: [
              { target: { schema: [...SUPABASE_SYSTEM_SCHEMAS] } },
              {
                target: {
                  kind: "schema",
                  name: [...SUPABASE_SYSTEM_SCHEMAS],
                },
              },
            ],
          },
        ],
      },
      action: "exclude",
    },
  ],
};
