-- state A: partitioned parent with an identity column, created BEFORE the
-- SEQUENCES default privilege below, so its backing sequence carries no grant.
-- Repartitioning replaces the parent; the recreated identity sequence must not
-- keep the grant the still-active default privilege injects.
DO $$ BEGIN CREATE ROLE corpus_idseq_part_r NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE SCHEMA s1;

CREATE TABLE s1.parent (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_on date NOT NULL DEFAULT '2024-06-01',
  period date NOT NULL DEFAULT '2024-06-01'
) PARTITION BY RANGE (created_on);

ALTER DEFAULT PRIVILEGES IN SCHEMA s1 GRANT USAGE ON SEQUENCES TO corpus_idseq_part_r;

CREATE TABLE s1.p1 PARTITION OF s1.parent
  FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
