-- state B: same shape partitioned by `period`; the identity sequence still
-- predates the default privilege and carries no grant.
DO $$ BEGIN CREATE ROLE corpus_idseq_part_r NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE SCHEMA s1;

CREATE TABLE s1.parent (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_on date NOT NULL DEFAULT '2024-06-01',
  period date NOT NULL DEFAULT '2024-06-01'
) PARTITION BY RANGE (period);

ALTER DEFAULT PRIVILEGES IN SCHEMA s1 GRANT USAGE ON SEQUENCES TO corpus_idseq_part_r;

CREATE TABLE s1.p1 PARTITION OF s1.parent
  FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
