import { CreateChange } from "../../base.change.ts";
import type { Table } from "../table.model.ts";

/**
 * Create a table.
 *
 * @see https://www.postgresql.org/docs/17/sql-createtable.html
 *
 * Synopsis
 * ```sql
 * CREATE [ [ GLOBAL | LOCAL ] { TEMPORARY | TEMP } | UNLOGGED ] TABLE [ IF NOT EXISTS ] table_name ( [
 *   { column_name data_type [ COLLATE collation ] [ column_constraint [ ... ] ]
 *     | table_constraint
 *     | LIKE source_table [ like_option ... ] }
 *     [, ... ]
 * ] )
 * [ INHERITS ( parent_table [, ... ] ) ]
 * [ PARTITION BY { RANGE | LIST | HASH } ( { column_name | ( expression ) } [, ... ] ) ]
 * [ USING method ]
 * [ WITH ( storage_parameter [= value] [, ... ] ) | WITHOUT OIDS ]
 * [ ON COMMIT { PRESERVE ROWS | DELETE ROWS | DROP } ]
 * [ TABLESPACE tablespace_name ]
 * ```
 */
export class CreateTable extends CreateChange {
  public readonly table: Table;

  constructor(props: { table: Table }) {
    super();
    this.table = props.table;
  }

  get stableId(): string {
    return `${this.table.stableId}`;
  }

  serialize(): string {
    const parts: string[] = ["CREATE"];

    // Add TEMPORARY/UNLOGGED based on persistence
    if (this.table.persistence === "t") {
      parts.push("TEMPORARY");
    } else if (this.table.persistence === "u") {
      parts.push("UNLOGGED");
    }

    parts.push("TABLE");

    // Add schema and name
    parts.push(`${this.table.schema}.${this.table.name}`);

    // If this is a partition (child) table, emit PARTITION OF ... FOR VALUES ...
    if (
      this.table.parent_schema &&
      this.table.parent_name &&
      this.table.partition_bound
    ) {
      return [
        ...parts,
        "PARTITION OF",
        `${this.table.parent_schema}.${this.table.parent_name}`,
        this.table.partition_bound,
      ].join(" ");
    }

    // Add columns definition
    if (this.table.columns.length === 0) {
      parts.push("()");
    } else {
      const columnDefinitions = this.table.columns.map((col) => {
        const tokens: string[] = [];

        // Column name
        tokens.push(col.name);

        // Data type (use formatted type string from the catalog)
        tokens.push(col.data_type_str);

        // Collation
        if (col.collation) {
          tokens.push("COLLATE", col.collation);
        }

        // Identity / generated / default
        if (col.is_identity) {
          tokens.push(
            col.is_identity_always
              ? "GENERATED ALWAYS AS IDENTITY"
              : "GENERATED BY DEFAULT AS IDENTITY",
          );
        } else if (col.is_generated && col.default) {
          // Generated stored columns expose their expression via pg_attrdef
          tokens.push(`GENERATED ALWAYS AS (${col.default}) STORED`);
        } else if (col.default) {
          tokens.push("DEFAULT", col.default);
        }

        // Nullability
        if (col.not_null) {
          tokens.push("NOT NULL");
        }

        return tokens.join(" ");
      });

      parts.push(`(${columnDefinitions.join(", ")})`);
    }

    // Add INHERITS if parent table exists (non-partition inheritance only)
    if (
      this.table.parent_schema &&
      this.table.parent_name &&
      !this.table.partition_bound
    ) {
      parts.push(
        "INHERITS",
        `(${this.table.parent_schema}.${this.table.parent_name})`,
      );
    }

    // Add PARTITION BY if this is a partitioned table (parent)
    if (this.table.partition_by) {
      parts.push("PARTITION BY", this.table.partition_by);
    }

    // Add storage parameters if specified
    if (this.table.options && this.table.options.length > 0) {
      parts.push("WITH", `(${this.table.options.join(", ")})`);
    }

    return parts.join(" ");
  }
}
