/**
 * Supabase policy package: filtering rules for Supabase-managed PostgreSQL
 * databases (target-architecture §3.9, stage-08-policy).
 *
 * Port of packages/pg-delta/src/core/integrations/supabase.ts into DSL v2.
 * v2 semantics: rules evaluated in order, first match wins, no match → include.
 * Rule ordering: specific INCLUDE rules first, then EXCLUDE rules.
 *
 * OLD RULE → NEW RULE MAPPING (for audit completeness)
 *
 * Old-1: objectType extension + operation create
 *        → { kind:"extension", verb:"add" } → include
 *
 * Old-2: objectType extension + operation drop
 *        → { kind:"extension", verb:"remove" } → include
 *
 * Old-3: objectType trigger AND trigger-schema IN SYSTEM
 *        AND NOT trigger-function_schema IN SYSTEM
 *        AND NOT (schema=pgmq AND table matches q_/a_ prefix)
 *        → { kind:"trigger", schema IN SYSTEM, not edgeTo{kind:"procedure", schema IN SYSTEM},
 *            not (schema=pgmq AND table glob q_* or a_*) } → include
 *
 * Old-4: "star-slash-schema" IN SUPABASE_SYSTEM_SCHEMAS
 *        → { schema: SUPABASE_SYSTEM_SCHEMAS } → exclude
 *
 * Old-5: "schema/name" IN SUPABASE_SYSTEM_SCHEMAS
 *        → { kind:"schema", name: SUPABASE_SYSTEM_SCHEMAS } → exclude
 *
 * Old-6: "star-slash-owner" IN SUPABASE_SYSTEM_ROLES
 *        → { owner: SUPABASE_SYSTEM_ROLES } → exclude
 *
 * Old-7: "role/name" IN SUPABASE_SYSTEM_ROLES
 *        → { kind:"role", name: SUPABASE_SYSTEM_ROLES } → exclude
 *
 * Old-8: membership where member OR role is a system role
 *        → { kind:"membership", idField{field:"member"} IN SYSTEM_ROLES } → exclude
 *           { kind:"membership", idField{field:"role"} IN SYSTEM_ROLES } → exclude
 *
 * Old-9: objectType foreign_data_wrapper + scope privilege
 *        → { kind:"acl", target:{kind:"fdw"} } → exclude
 *        (GRANT/REVOKE on FDW requires superuser; non-superuser postgres
 *        cannot replay this ACL regardless of FDW ownership)
 *
 * Old-10: implicitly filtered in old engine via parent-object exclusion
 *         → { kind:["acl","comment","securityLabel"], target:{schema IN SYSTEM} } → exclude
 *            { kind:["acl","comment","securityLabel"], target:{kind:"schema", name IN SYSTEM_SCHEMAS} } → exclude
 *         Two sub-rules under the unified target predicate: target.schema covers
 *         qualified-kind targets (table, view, sequence...) while target.kind+name
 *         covers simple-kind targets like schema itself (in v2, satellite deltas
 *         are independent; must be excluded explicitly)
 *
 * Old-11: emptyCatalog: undefined (TODO in old engine)
 *         → baseline: "supabase-baseline"
 *         (snapshot generated by scripts/generate-supabase-baseline.ts)
 *
 * Old-12: Wasm FDW filtering via wasm_fdw_handler/validator function names
 *         → OBSOLETE in new engine: extraction-time pg_depend 'e' rows
 *         exclude extension-member FDWs, servers, foreign tables, user
 *         mappings at extract time. The precise Wasm-name match is not
 *         ported; if extension-member objects slip through, the owner
 *         predicate or ownedByExtension predicate covers them.
 *
 * Old-13: serialize skipAuthorization for schema CREATE owned by system role
 *         → serialize rule: { kind: schema, owner: SYSTEM_ROLES } sets
 *         skipAuthorization — the planner applies serialize params PER
 *         MATCHED FACT (first-match-wins), so user schemas keep their
 *         AUTHORIZATION clause
 *
 * Old-14: serialize skipSchema for extensions installing their own schema
 *         → REMOVED. The SCHEMA clause is now derived from the extension's
 *         `relocatable` fact (pg_extension.extrelocatable): a non-relocatable
 *         extension emits a bare CREATE EXTENSION. No name list, not
 *         Supabase-specific. See docs/architecture/managed-view-architecture.md (move 2).
 *
 * BASELINE
 * The baseline field names the snapshot that represents "empty" on a Supabase
 * platform instance. Facts present-and-identical in the baseline are subtracted
 * before diffing (via subtractBaseline), replacing the old emptyCatalog TODO.
 * Regenerate: bun run scripts/generate-supabase-baseline.ts <db-url> <pg-major>
 */

import type { Policy } from "./policy.ts";

// ---------------------------------------------------------------------------
// Lists copied VERBATIM from packages/pg-delta/src/core/integrations/supabase.ts
// ---------------------------------------------------------------------------

/** Supabase system schemas that should be excluded from user plans. */
export const SUPABASE_SYSTEM_SCHEMAS = [
  "_analytics",
  "_realtime",
  "_supavisor",
  "auth",
  "cron",
  "etl",
  "extensions",
  "graphql",
  "graphql_public",
  "information_schema",
  "net",
  "pgbouncer",
  "pgmq",
  "pgmq_public",
  "pgsodium",
  "pgsodium_masks",
  "pgtle",
  "realtime",
  "storage",
  "supabase_functions",
  "supabase_migrations",
  "vault",
] as const;

/** Supabase system roles that should be excluded from user plans. */
export const SUPABASE_SYSTEM_ROLES = [
  "anon",
  "authenticated",
  "authenticator",
  "cli_login_postgres",
  "dashboard_user",
  "pgbouncer",
  "pgsodium_keyholder",
  "pgsodium_keyiduser",
  "pgsodium_keymaker",
  "pgtle_admin",
  "service_role",
  "supabase_admin",
  "supabase_auth_admin",
  "supabase_etl_admin",
  "supabase_functions_admin",
  "supabase_read_only_user",
  "supabase_realtime_admin",
  "supabase_replication_admin",
  "supabase_storage_admin",
  "supabase_superuser",
] as const;

// ---------------------------------------------------------------------------
// The Supabase policy
// ---------------------------------------------------------------------------

/**
 * The Supabase policy: port of every filterable behavior from the old
 * supabase.ts into DSL v2.
 */
export const supabasePolicy: Policy = {
  id: "supabase",

  // baseline (intentionally UNSET in v1): a baseline names the snapshot that
  // represents "empty" on a Supabase instance; facts present-and-identical in
  // it are subtracted before diffing (resolveBaseline → plan options.baseline),
  // so platform-managed objects are invisible without a filter rule per object.
  // No Supabase baseline snapshot is committed yet (a separate v1 validation
  // item), so this policy does NOT declare one — a declared-but-unresolved
  // baseline now fail-fasts (review finding 3) rather than being silently
  // ignored. The `filter` rules below already hide platform objects; when the
  // baseline snapshot lands, re-add `baseline: "supabase-baseline"` here and
  // resolveBaseline will subtract it. Generate with:
  //   bun run scripts/generate-supabase-baseline.ts <db-url> <pg-major>

  serialize: [
    // Old-13 (REMOVED): the skipAuthorization serialize rule is no longer needed.
    // With owner-as-edge (move 2), when a schema is owned by a system role that
    // is excluded from the view, the owner edge is pruned by buildFactBase before
    // diffing — so no owner edge exists → no ALTER SCHEMA … OWNER TO is emitted
    // → CREATE SCHEMA renders without AUTHORIZATION by construction, not via param.
    // See docs/architecture/managed-view-architecture.md (move 2).
    //
    // Old-14 (REMOVED): the SCHEMA clause is now derived from the extension's
    // `relocatable` fact (pg_extension.extrelocatable) in the extension rule —
    // a non-relocatable extension (pgmq / pgsodium / pgtle) emits a bare
    // CREATE EXTENSION with no name list and nothing Supabase-specific.
    // See docs/architecture/managed-view-architecture.md (move 2).
  ],

  filter: [
    // -------------------------------------------------------------------------
    // INCLUDE rules (specific cases that must survive system-level exclusions)
    // Must appear BEFORE the exclude rules (first-match-wins).
    // -------------------------------------------------------------------------

    // Rule 1+2 (old rules): include extension CREATE and DROP operations.
    // Extensions are always user-declarable state on Supabase regardless of
    // the schema they install into. Place before the system-schema/owner
    // exclusions so e.g. `CREATE EXTENSION pgmq` (schema=pgmq) is not filtered.
    {
      match: { all: [{ kind: "extension" }, { verb: ["add", "remove"] }] },
      action: "include",
    },

    // Rule 3 (old rule): include user-created triggers on tables in managed
    // schemas. A trigger lives in the schema of the table it fires on, so a
    // customer trigger on `auth.users` appears in the `auth` schema and would
    // otherwise be caught by the system-schema exclusion below.
    //
    // The discriminator is the trigger function's schema: Supabase's own
    // triggers call functions inside the same managed schema, while a user
    // trigger points to a function in `public` (or another non-managed schema).
    //
    // Defensive exclusion: pgmq dynamically creates `pgmq.q_<name>` /
    // `pgmq.a_<name>` tables via `pgmq.create()` rather than
    // `CREATE EXTENSION pgmq`, so the extraction-time pg_depend 'e' guard may
    // miss them. Exclude triggers on those tables explicitly.
    {
      match: {
        all: [
          { kind: "trigger" },
          // trigger is on a table in a managed schema
          { schema: [...SUPABASE_SYSTEM_SCHEMAS] },
          // trigger function lives outside the managed schemas (user-owned)
          {
            not: {
              edgeTo: {
                kind: "procedure",
                schema: [...SUPABASE_SYSTEM_SCHEMAS],
              },
            },
          },
          // not a trigger on a pgmq queue / archive table
          {
            not: {
              all: [
                { schema: "pgmq" },
                {
                  any: [
                    { idField: { field: "table", glob: "q_*" } },
                    { idField: { field: "table", glob: "a_*" } },
                  ],
                },
              ],
            },
          },
        ],
      },
      action: "include",
    },

    // -------------------------------------------------------------------------
    // EXCLUDE rules — system objects the user cannot / should not manage
    // -------------------------------------------------------------------------

    // Rule 4 (old rule): exclude any fact whose identity schema is a system schema.
    // Covers: table, view, materializedView, foreignTable, sequence, index,
    // collation, domain, type, column, constraint, trigger, rule, policy,
    // procedure, aggregate — every qualified-kind or sub-entity kind.
    {
      match: { schema: [...SUPABASE_SYSTEM_SCHEMAS] },
      action: "exclude",
    },

    // Rule 5 (old rule): exclude schema objects whose OWN name is a system schema.
    // The `schema` predicate checks `fact.id.schema`, not `fact.id.name`, so
    // a `{ kind: "schema", name: "auth" }` fact has no `schema` field.
    // This rule closes that gap.
    {
      match: {
        all: [{ kind: "schema" }, { name: [...SUPABASE_SYSTEM_SCHEMAS] }],
      },
      action: "exclude",
    },

    // Rule 6 (old rule): exclude objects whose payload owner is a system role.
    // Covers tables, views, schemas, sequences, etc. that are managed by
    // Supabase system roles.
    {
      match: { owner: [...SUPABASE_SYSTEM_ROLES] },
      action: "exclude",
    },

    // Rule 7 (old rule): exclude role objects whose name is a system role.
    // The `owner` predicate reads payload["owner"], not the role's own name.
    {
      match: {
        all: [{ kind: "role" }, { name: [...SUPABASE_SYSTEM_ROLES] }],
      },
      action: "exclude",
    },

    // Rule 8a (old rule): exclude memberships where the MEMBER is a system role.
    {
      match: {
        all: [
          { kind: "membership" },
          { idField: { field: "member", glob: [...SUPABASE_SYSTEM_ROLES] } },
        ],
      },
      action: "exclude",
    },

    // Rule 8b (old rule): exclude memberships where the ROLE (grantee) is a system role.
    {
      match: {
        all: [
          { kind: "membership" },
          { idField: { field: "role", glob: [...SUPABASE_SYSTEM_ROLES] } },
        ],
      },
      action: "exclude",
    },

    // Rule 9 (old rule): exclude ACL facts on FDWs.
    //
    // GRANT/REVOKE on FOREIGN DATA WRAPPER requires superuser (verified:
    // tests/capability.test.ts "a non-superuser cannot GRANT on a FOREIGN DATA
    // WRAPPER"). On Supabase Cloud `postgres` has the elevated rights, but the
    // local Docker image does not, so `supabase db reset` aborts with
    // "permission denied for foreign-data wrapper". The owner rule above
    // already covers wrappers owned by `supabase_admin`, but pg_dump rewrites
    // OWNER TO to whoever ran the dump, so after a restore the FDW often ends
    // up owned by `postgres` and slips past the owner gate. Since a
    // non-superuser `postgres` cannot grant on any FDW regardless of ownership,
    // the ACL diff is not user-replayable. We do NOT apply the same blanket
    // rule to FOREIGN SERVER: server GRANT/REVOKE does not require superuser
    // and user-created servers carry legitimate user ACL that must roundtrip.
    //
    // RETAINED, not retired (follow-up 2). The applier-capability mechanism
    // (move 6, capabilityExcludedRoots) now derives this exclusion precisely:
    // it drops FDW ACLs whenever the applier is non-superuser. The two are at
    // parity for the real Supabase flow (local + Cloud `postgres` are both
    // non-superuser). They DIVERGE for a superuser applier — capability would
    // (correctly) MANAGE the FDW ACL, while this rule excludes unconditionally.
    // This rule is kept because it is a SELF-CONTAINED policy guarantee: the
    // exclusion holds even if a caller forgets to probe + pass capability,
    // whereas capability depends on every caller supplying it. Capability is
    // the general mechanism (any non-superuser applier, any policy); this rule
    // is the Supabase policy's unconditional belt-and-suspenders. See
    // docs/architecture/managed-view-architecture.md (follow-up 2).
    {
      match: {
        all: [{ kind: "acl" }, { target: { kind: "fdw" } }],
      },
      action: "exclude",
    },

    // Rule 10 (implicit in old engine): exclude ACL, comment, and security-label
    // satellite facts whose TARGET object lives in a system schema.
    //
    // In the old engine, satellite facts for system-schema objects were filtered
    // implicitly because the parent object was excluded first and satellites
    // cascaded. In v2, each delta is evaluated independently against the full
    // fact base, so we must explicitly exclude satellites targeting system objects.
    //
    // Two sub-rules under the unified `target` predicate:
    //   - target.schema covers qualified-kind targets (table, view, sequence, ...)
    //     which carry a `schema` field in their StableId.
    //   - target.kind + target.name covers simple-kind targets like schema
    //     which carry only a `name` field (no `schema`). We match schema-kind
    //     targets whose `name` is in SUPABASE_SYSTEM_SCHEMAS (covers ACLs on
    //     the auth schema itself, not just tables inside auth).
    {
      match: {
        all: [
          { kind: ["acl", "comment", "securityLabel"] },
          {
            any: [
              { target: { schema: [...SUPABASE_SYSTEM_SCHEMAS] } },
              {
                target: {
                  kind: "schema",
                  name: [...SUPABASE_SYSTEM_SCHEMAS],
                },
              },
            ],
          },
        ],
      },
      action: "exclude",
    },
  ],
};
