create table app.projects (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references app.organizations(id) on delete cascade,
    owner_id bigint references app.users(id) on delete set null,
    ref uuid not null default extensions.uuid_generate_v4() unique,
    slug app.slug_text not null,
    name text not null,
    inserted_at timestamp without time zone default timezone('utc', now()) not null,
    updated_at timestamp without time zone default timezone('utc', now()) not null,
    constraint projects_slug_check check (app.slug_ok(slug))
);

alter table app.projects
    add column project_order bigint default nextval('app.project_order_seq'::regclass);

alter sequence app.project_order_seq
    owned by app.projects.project_order;

create trigger projects_touch_updated_at
    before update
    on app.projects
    for each row
execute function app.touch_updated_at();

alter table app.projects
    enable row level security;

create policy projects_read_policy
    on app.projects
    for select
    using (true);

create policy projects_write_policy
    on app.projects
    for update
    using (true)
    with check (true);

comment on table app.projects is 'Core projects table';
comment on column app.projects.slug is 'Normalized slug';

alter table app.projects owner to app_owner;

grant select, insert, update on table app.projects to app_writer;
revoke update on table app.projects from app_reader;
