create table app.users (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references app.organizations(id) on delete cascade,
    gotrue_id uuid not null unique,
    email text not null,
    profile app.address,
    status app.status not null default 'draft',
    inserted_at timestamp without time zone default timezone('utc', now()) not null,
    updated_at timestamp without time zone default timezone('utc', now()) not null
);
