-- state B: identity column created BEFORE the default privilege, so its
-- backing sequence has no grant for the role.
DO $$ BEGIN CREATE ROLE corpus_idseq_add_r NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE SCHEMA test_schema;
CREATE TABLE test_schema.t_ident (id bigint GENERATED BY DEFAULT AS IDENTITY, v int);
ALTER DEFAULT PRIVILEGES IN SCHEMA test_schema GRANT USAGE ON SEQUENCES TO corpus_idseq_add_r;
