import { afterAll, describe, expect, test } from "bun:test";
import { validateAnalyzeResultWithPostgres } from "./support/postgres-validation";
import { analyzeAndSortFromRandomizedStatements } from "./support/randomized-runtime-analysis";
import { createTempFixtureHarness } from "./support/temp-fixture";

const fixtures = createTempFixtureHarness("pg-topo-fn-chain-");
const createSqlFixture = fixtures.createSqlFixture;

afterAll(fixtures.cleanup);

const createComplexFunctionChainFixture = async (): Promise<string> =>
  createSqlFixture({
    "00_view_project_exports.sql": `
create view app.project_exports as
select
    p.id,
    app.project_export_row(p.id) as export_key
from app.projects p;
`,
    "01_fn_project_export_row.sql": `
create function app.project_export_row(project_id bigint) returns text
    language plpgsql
as $$
declare
    slug text;
    organization_slug text;
begin
    select
        app.project_slug(project_id),
        o.slug
    into
        slug,
        organization_slug
    from app.projects p
    join app.organizations o on o.id = p.organization_id
    where p.id = project_id;

    return app.slugify(organization_slug || '-' || slug);
end;
$$;
`,
    "02_fn_project_slug.sql": `
create function app.project_slug(project_id bigint) returns text
    language sql
    stable
as $$
    select app.slugify(app.project_owner_label(project_id) || '-' || p.name)
    from app.projects p
    where p.id = project_id;
$$;
`,
    "03_fn_project_owner_label.sql": `
create function app.project_owner_label(project_id bigint) returns text
    language sql
    stable
as $$
    select app.slugify(app.user_display_name(p.owner_id))
    from app.projects p
    where p.id = project_id;
$$;
`,
    "04_fn_user_display_name.sql": `
create function app.user_display_name(user_id bigint) returns text
    language sql
    stable
as $$
    select lower(u.email)
    from app.users u
    where u.id = user_id;
$$;
`,
    "05_fn_slugify.sql": `
create function app.slugify(input text) returns text
    language sql
    immutable
as $$
    select lower(regexp_replace(input, '[^a-zA-Z0-9-]+', '-', 'g'));
$$;
`,
    "06_table_projects.sql": `
create table app.projects (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references app.organizations(id),
    owner_id bigint not null references app.users(id),
    name text not null
);
`,
    "07_table_users.sql": `
create table app.users (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references app.organizations(id),
    email text not null
);
`,
    "08_table_organizations.sql": `
create table app.organizations (
    id bigint generated by default as identity primary key,
    slug text not null
);
`,
    "09_schema.sql": `
create schema app;
`,
  });

describe("function body dependency chains", () => {
  test("randomized function/table dependency chains still execute at runtime", async () => {
    const root = await createComplexFunctionChainFixture();
    const result = await analyzeAndSortFromRandomizedStatements({
      roots: [root],
      seed: 47,
    });
    const validation = await validateAnalyzeResultWithPostgres(result);
    const executionErrors = validation.diagnostics.filter(
      (diagnostic) => diagnostic.code === "RUNTIME_EXECUTION_ERROR",
    );

    expect(executionErrors).toHaveLength(0);
  }, 120000);
});
