CREATE SCHEMA test_schema;
CREATE SEQUENCE test_schema.items_c1_seq;
CREATE TABLE test_schema.items (
  c1 int NOT NULL DEFAULT nextval('test_schema.items_c1_seq'::regclass),
  c2 int GENERATED ALWAYS AS IDENTITY,
  c3 int GENERATED BY DEFAULT AS IDENTITY
);
ALTER SEQUENCE test_schema.items_c1_seq OWNED BY test_schema.items.c1;
