import type { PgDepend } from "./depend.ts";
import type { Aggregate } from "./objects/aggregate/aggregate.model.ts";
import type { TableLikeObject } from "./objects/base.model.ts";
import type { Collation } from "./objects/collation/collation.model.ts";
import type { Domain } from "./objects/domain/domain.model.ts";
import type { EventTrigger } from "./objects/event-trigger/event-trigger.model.ts";
import type { Extension } from "./objects/extension/extension.model.ts";
import type { ForeignDataWrapper } from "./objects/foreign-data-wrapper/foreign-data-wrapper/foreign-data-wrapper.model.ts";
import type { ForeignTable } from "./objects/foreign-data-wrapper/foreign-table/foreign-table.model.ts";
import type { Server } from "./objects/foreign-data-wrapper/server/server.model.ts";
import type { UserMapping } from "./objects/foreign-data-wrapper/user-mapping/user-mapping.model.ts";
import type { Index } from "./objects/index/index.model.ts";
import type { MaterializedView } from "./objects/materialized-view/materialized-view.model.ts";
import type { Procedure } from "./objects/procedure/procedure.model.ts";
import type { Publication } from "./objects/publication/publication.model.ts";
import type { RlsPolicy } from "./objects/rls-policy/rls-policy.model.ts";
import type { Role } from "./objects/role/role.model.ts";
import type { Rule } from "./objects/rule/rule.model.ts";
import type { Schema } from "./objects/schema/schema.model.ts";
import type { Sequence } from "./objects/sequence/sequence.model.ts";
import type { Subscription } from "./objects/subscription/subscription.model.ts";
import type { Table } from "./objects/table/table.model.ts";
import type { Trigger } from "./objects/trigger/trigger.model.ts";
import type { CompositeType } from "./objects/type/composite-type/composite-type.model.ts";
import type { Enum } from "./objects/type/enum/enum.model.ts";
import type { Range } from "./objects/type/range/range.model.ts";
import type { View } from "./objects/view/view.model.ts";

interface CatalogProps {
  aggregates: Record<string, Aggregate>;
  collations: Record<string, Collation>;
  compositeTypes: Record<string, CompositeType>;
  domains: Record<string, Domain>;
  enums: Record<string, Enum>;
  extensions: Record<string, Extension>;
  procedures: Record<string, Procedure>;
  indexes: Record<string, Index>;
  materializedViews: Record<string, MaterializedView>;
  subscriptions: Record<string, Subscription>;
  publications: Record<string, Publication>;
  rlsPolicies: Record<string, RlsPolicy>;
  roles: Record<string, Role>;
  schemas: Record<string, Schema>;
  sequences: Record<string, Sequence>;
  tables: Record<string, Table>;
  triggers: Record<string, Trigger>;
  eventTriggers: Record<string, EventTrigger>;
  rules: Record<string, Rule>;
  ranges: Record<string, Range>;
  views: Record<string, View>;
  foreignDataWrappers: Record<string, ForeignDataWrapper>;
  servers: Record<string, Server>;
  userMappings: Record<string, UserMapping>;
  foreignTables: Record<string, ForeignTable>;
  depends: PgDepend[];
  indexableObjects: Record<string, TableLikeObject>;
  version: number;
  currentUser: string;
}

export class Catalog {
  public readonly aggregates: CatalogProps["aggregates"];
  public readonly collations: CatalogProps["collations"];
  public readonly compositeTypes: CatalogProps["compositeTypes"];
  public readonly domains: CatalogProps["domains"];
  public readonly enums: CatalogProps["enums"];
  public readonly extensions: CatalogProps["extensions"];
  public readonly procedures: CatalogProps["procedures"];
  public readonly indexes: CatalogProps["indexes"];
  public readonly materializedViews: CatalogProps["materializedViews"];
  public readonly subscriptions: CatalogProps["subscriptions"];
  public readonly publications: CatalogProps["publications"];
  public readonly rlsPolicies: CatalogProps["rlsPolicies"];
  public readonly roles: CatalogProps["roles"];
  public readonly schemas: CatalogProps["schemas"];
  public readonly sequences: CatalogProps["sequences"];
  public readonly tables: CatalogProps["tables"];
  public readonly triggers: CatalogProps["triggers"];
  public readonly eventTriggers: CatalogProps["eventTriggers"];
  public readonly rules: CatalogProps["rules"];
  public readonly ranges: CatalogProps["ranges"];
  public readonly views: CatalogProps["views"];
  public readonly foreignDataWrappers: CatalogProps["foreignDataWrappers"];
  public readonly servers: CatalogProps["servers"];
  public readonly userMappings: CatalogProps["userMappings"];
  public readonly foreignTables: CatalogProps["foreignTables"];
  public readonly depends: CatalogProps["depends"];
  public readonly indexableObjects: CatalogProps["indexableObjects"];
  public readonly version: CatalogProps["version"];
  public readonly currentUser: CatalogProps["currentUser"];

  constructor(props: CatalogProps) {
    this.aggregates = props.aggregates;
    this.collations = props.collations;
    this.compositeTypes = props.compositeTypes;
    this.domains = props.domains;
    this.enums = props.enums;
    this.extensions = props.extensions;
    this.procedures = props.procedures;
    this.indexes = props.indexes;
    this.materializedViews = props.materializedViews;
    this.subscriptions = props.subscriptions;
    this.publications = props.publications;
    this.rlsPolicies = props.rlsPolicies;
    this.roles = props.roles;
    this.schemas = props.schemas;
    this.sequences = props.sequences;
    this.tables = props.tables;
    this.triggers = props.triggers;
    this.eventTriggers = props.eventTriggers;
    this.rules = props.rules;
    this.ranges = props.ranges;
    this.views = props.views;
    this.foreignDataWrappers = props.foreignDataWrappers;
    this.servers = props.servers;
    this.userMappings = props.userMappings;
    this.foreignTables = props.foreignTables;
    this.depends = props.depends;
    this.indexableObjects = props.indexableObjects;
    this.version = props.version;
    this.currentUser = props.currentUser;
  }
}
