/**
 * The rule table (target-architecture §3.4): the ONLY per-kind logic in the
 * system. Structured data — functions confined to template slots
 * (guardrail 3). Each rule maps facts/attribute-changes to SQL plus the
 * dependency metadata the graph needs.
 */
import type { Fact } from "../core/fact.ts";
import type { PayloadValue } from "../core/hash.ts";
import type { StableId } from "../core/stable-id.ts";
import { commentTarget, grantTarget, lit, qid, rel, routineSig } from "./render.ts";

export interface ActionSpec {
  sql: string;
  /** extra consumed ids beyond the fact's parent (which is implicit) */
  consumes?: StableId[];
  dataLoss?: "none" | "destructive";
  rewriteRisk?: boolean;
}

export type AttributeRule =
  | { alter: (fact: Fact, from: PayloadValue, to: PayloadValue) => ActionSpec }
  | "replace";

export interface KindRules {
  create(fact: Fact): ActionSpec[];
  drop(fact: Fact): ActionSpec;
  attributes: Record<string, AttributeRule>;
  /** kind weight for deterministic tie-breaking (pg_dump-inspired) */
  weight: number;
}

const str = (v: PayloadValue): string => String(v);

function p(fact: Fact, key: string): PayloadValue {
  return fact.payload[key];
}

/** Role attribute keyword map (CREATE ROLE / ALTER ROLE flags). */
const ROLE_FLAGS: Record<string, [on: string, off: string]> = {
  superuser: ["SUPERUSER", "NOSUPERUSER"],
  inherit: ["INHERIT", "NOINHERIT"],
  createRole: ["CREATEROLE", "NOCREATEROLE"],
  createDb: ["CREATEDB", "NOCREATEDB"],
  login: ["LOGIN", "NOLOGIN"],
  replication: ["REPLICATION", "NOREPLICATION"],
  bypassRls: ["BYPASSRLS", "NOBYPASSRLS"],
};

function roleFlagSql(payload: Fact["payload"]): string {
  return Object.entries(ROLE_FLAGS)
    .map(([key, [on, off]]) => (payload[key] ? on : off))
    .join(" ");
}

function ownerRule(alterPrefix: (fact: Fact) => string): AttributeRule {
  return {
    alter: (fact, _from, to) => ({
      sql: `${alterPrefix(fact)} OWNER TO ${qid(str(to))}`,
      consumes: [{ kind: "role", name: str(to) }],
    }),
  };
}

function columnRef(fact: Fact): { table: string; schema: string; column: string } {
  const id = fact.id as { schema: string; table: string; name: string };
  return { schema: id.schema, table: id.table, column: id.name };
}

function columnClause(fact: Fact): string {
  const { column } = columnRef(fact);
  const type = str(p(fact, "type"));
  let sql = `${qid(column)} ${type}`;
  const collation = p(fact, "collation");
  if (collation != null) sql += ` COLLATE ${str(collation)}`;
  const generated = p(fact, "generatedExpr");
  if (generated != null) sql += ` GENERATED ALWAYS AS (${str(generated)}) STORED`;
  const identity = p(fact, "identity");
  if (identity === "a") sql += ` GENERATED ALWAYS AS IDENTITY`;
  if (identity === "d") sql += ` GENERATED BY DEFAULT AS IDENTITY`;
  if (p(fact, "notNull")) sql += ` NOT NULL`;
  return sql;
}

const POLICY_CMD: Record<string, string> = {
  r: "SELECT",
  a: "INSERT",
  w: "UPDATE",
  d: "DELETE",
  "*": "ALL",
};

function policySql(fact: Fact): string {
  const id = fact.id as { schema: string; table: string; name: string };
  const roles = (p(fact, "roles") as string[]).map((r) => (r === "PUBLIC" ? "PUBLIC" : qid(r)));
  let sql = `CREATE POLICY ${qid(id.name)} ON ${rel(id.schema, id.table)}`;
  if (!p(fact, "permissive")) sql += ` AS RESTRICTIVE`;
  sql += ` FOR ${POLICY_CMD[str(p(fact, "cmd"))] ?? "ALL"}`;
  sql += ` TO ${roles.join(", ")}`;
  const using = p(fact, "usingExpr");
  if (using != null) sql += ` USING (${str(using)})`;
  const check = p(fact, "checkExpr");
  if (check != null) sql += ` WITH CHECK (${str(check)})`;
  return sql;
}

function grantActions(fact: Fact, verb: "grant"): ActionSpec[] {
  const id = fact.id as { kind: "acl"; target: StableId; grantee: string };
  const grantee = id.grantee === "PUBLIC" ? "PUBLIC" : qid(id.grantee);
  const privileges = p(fact, "privileges") as string[];
  const grantable = new Set((p(fact, "grantable") as string[]) ?? []);
  const plain = privileges.filter((priv) => !grantable.has(priv));
  const withOption = privileges.filter((priv) => grantable.has(priv));
  const consumes: StableId[] =
    id.grantee === "PUBLIC" ? [] : [{ kind: "role", name: id.grantee }];
  const specs: ActionSpec[] = [];
  if (plain.length > 0) {
    specs.push({
      sql: `GRANT ${plain.join(", ")} ON ${grantTarget(id.target)} TO ${grantee}`,
      consumes,
    });
  }
  if (withOption.length > 0) {
    specs.push({
      sql: `GRANT ${withOption.join(", ")} ON ${grantTarget(id.target)} TO ${grantee} WITH GRANT OPTION`,
      consumes,
    });
  }
  void verb;
  return specs;
}

export const RULES: Record<string, KindRules> = {
  role: {
    weight: 0,
    create: (fact) => [
      { sql: `CREATE ROLE ${qid((fact.id as { name: string }).name)} WITH ${roleFlagSql(fact.payload)}` },
    ],
    drop: (fact) => ({ sql: `DROP ROLE ${qid((fact.id as { name: string }).name)}` }),
    attributes: Object.fromEntries(
      Object.entries(ROLE_FLAGS).map(([key, [on, off]]) => [
        key,
        {
          alter: (fact: Fact, _from: PayloadValue, to: PayloadValue) => ({
            sql: `ALTER ROLE ${qid((fact.id as { name: string }).name)} WITH ${to ? on : off}`,
          }),
        },
      ]),
    ),
  },

  schema: {
    weight: 1,
    create: (fact) => [
      {
        sql: `CREATE SCHEMA ${qid((fact.id as { name: string }).name)} AUTHORIZATION ${qid(str(p(fact, "owner")))}`,
        consumes: [{ kind: "role", name: str(p(fact, "owner")) }],
      },
    ],
    drop: (fact) => ({ sql: `DROP SCHEMA ${qid((fact.id as { name: string }).name)}` }),
    attributes: {
      owner: ownerRule((fact) => `ALTER SCHEMA ${qid((fact.id as { name: string }).name)}`),
    },
  },

  extension: {
    weight: 2,
    create: (fact) => [
      {
        sql: `CREATE EXTENSION ${qid((fact.id as { name: string }).name)} SCHEMA ${qid(str(p(fact, "schema")))}`,
        consumes: [{ kind: "schema", name: str(p(fact, "schema")) }],
      },
    ],
    drop: (fact) => ({ sql: `DROP EXTENSION ${qid((fact.id as { name: string }).name)}` }),
    attributes: {
      schema: {
        alter: (fact, _from, to) => ({
          sql: `ALTER EXTENSION ${qid((fact.id as { name: string }).name)} SET SCHEMA ${qid(str(to))}`,
          consumes: [{ kind: "schema", name: str(to) }],
        }),
      },
    },
  },

  sequence: {
    weight: 3,
    create: (fact) => {
      const id = fact.id as { schema: string; name: string };
      return [
        {
          sql:
            `CREATE SEQUENCE ${rel(id.schema, id.name)} AS ${str(p(fact, "dataType"))}` +
            ` INCREMENT BY ${str(p(fact, "increment"))} MINVALUE ${str(p(fact, "minValue"))}` +
            ` MAXVALUE ${str(p(fact, "maxValue"))} START WITH ${str(p(fact, "start"))}` +
            ` CACHE ${str(p(fact, "cache"))} ${p(fact, "cycle") ? "CYCLE" : "NO CYCLE"}`,
          consumes: [{ kind: "role", name: str(p(fact, "owner")) }],
        },
      ];
    },
    drop: (fact) => {
      const id = fact.id as { schema: string; name: string };
      return { sql: `DROP SEQUENCE ${rel(id.schema, id.name)}` };
    },
    attributes: {
      owner: ownerRule((fact) => {
        const id = fact.id as { schema: string; name: string };
        return `ALTER SEQUENCE ${rel(id.schema, id.name)}`;
      }),
      dataType: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return { sql: `ALTER SEQUENCE ${rel(id.schema, id.name)} AS ${str(to)}` };
        },
      },
      increment: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return { sql: `ALTER SEQUENCE ${rel(id.schema, id.name)} INCREMENT BY ${str(to)}` };
        },
      },
      minValue: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return { sql: `ALTER SEQUENCE ${rel(id.schema, id.name)} MINVALUE ${str(to)}` };
        },
      },
      maxValue: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return { sql: `ALTER SEQUENCE ${rel(id.schema, id.name)} MAXVALUE ${str(to)}` };
        },
      },
      start: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return { sql: `ALTER SEQUENCE ${rel(id.schema, id.name)} START WITH ${str(to)}` };
        },
      },
      cache: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return { sql: `ALTER SEQUENCE ${rel(id.schema, id.name)} CACHE ${str(to)}` };
        },
      },
      cycle: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return { sql: `ALTER SEQUENCE ${rel(id.schema, id.name)} ${to ? "CYCLE" : "NO CYCLE"}` };
        },
      },
    },
  },

  table: {
    weight: 4,
    create: (fact) => {
      const id = fact.id as { schema: string; name: string };
      const persistence = str(p(fact, "persistence"));
      const specs: ActionSpec[] = [
        {
          sql: `CREATE ${persistence === "u" ? "UNLOGGED " : ""}TABLE ${rel(id.schema, id.name)} ()`,
          consumes: [{ kind: "role", name: str(p(fact, "owner")) }],
        },
      ];
      if (p(fact, "rowSecurity")) {
        specs.push({ sql: `ALTER TABLE ${rel(id.schema, id.name)} ENABLE ROW LEVEL SECURITY` });
      }
      if (p(fact, "forceRowSecurity")) {
        specs.push({ sql: `ALTER TABLE ${rel(id.schema, id.name)} FORCE ROW LEVEL SECURITY` });
      }
      if (str(p(fact, "owner")) !== "") {
        specs.push({
          sql: `ALTER TABLE ${rel(id.schema, id.name)} OWNER TO ${qid(str(p(fact, "owner")))}`,
          consumes: [{ kind: "role", name: str(p(fact, "owner")) }],
        });
      }
      return specs;
    },
    drop: (fact) => {
      const id = fact.id as { schema: string; name: string };
      return { sql: `DROP TABLE ${rel(id.schema, id.name)}`, dataLoss: "destructive" };
    },
    attributes: {
      owner: ownerRule((fact) => {
        const id = fact.id as { schema: string; name: string };
        return `ALTER TABLE ${rel(id.schema, id.name)}`;
      }),
      persistence: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return {
            sql: `ALTER TABLE ${rel(id.schema, id.name)} SET ${str(to) === "u" ? "UNLOGGED" : "LOGGED"}`,
            rewriteRisk: true,
          };
        },
      },
      rowSecurity: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return {
            sql: `ALTER TABLE ${rel(id.schema, id.name)} ${to ? "ENABLE" : "DISABLE"} ROW LEVEL SECURITY`,
          };
        },
      },
      forceRowSecurity: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string };
          return {
            sql: `ALTER TABLE ${rel(id.schema, id.name)} ${to ? "FORCE" : "NO FORCE"} ROW LEVEL SECURITY`,
          };
        },
      },
    },
  },

  column: {
    weight: 5,
    create: (fact) => {
      const { schema, table } = columnRef(fact);
      return [{ sql: `ALTER TABLE ${rel(schema, table)} ADD COLUMN ${columnClause(fact)}` }];
    },
    drop: (fact) => {
      const { schema, table, column } = columnRef(fact);
      return {
        sql: `ALTER TABLE ${rel(schema, table)} DROP COLUMN ${qid(column)}`,
        dataLoss: "destructive",
      };
    },
    attributes: {
      type: {
        alter: (fact, _from, to) => {
          const { schema, table, column } = columnRef(fact);
          return {
            sql: `ALTER TABLE ${rel(schema, table)} ALTER COLUMN ${qid(column)} TYPE ${str(to)}`,
            rewriteRisk: true,
          };
        },
      },
      notNull: {
        alter: (fact, _from, to) => {
          const { schema, table, column } = columnRef(fact);
          return {
            sql: `ALTER TABLE ${rel(schema, table)} ALTER COLUMN ${qid(column)} ${to ? "SET" : "DROP"} NOT NULL`,
          };
        },
      },
      identity: {
        alter: (fact, from, to) => {
          const { schema, table, column } = columnRef(fact);
          const target = `ALTER TABLE ${rel(schema, table)} ALTER COLUMN ${qid(column)}`;
          if (to == null) return { sql: `${target} DROP IDENTITY` };
          const phrase = to === "a" ? "GENERATED ALWAYS" : "GENERATED BY DEFAULT";
          if (from == null) return { sql: `${target} ADD ${phrase} AS IDENTITY` };
          return { sql: `${target} SET ${phrase}` };
        },
      },
      collation: "replace",
      generatedExpr: "replace",
    },
  },

  default: {
    weight: 6,
    create: (fact) => {
      const { schema, table, column } = columnRef(fact);
      return [
        {
          sql: `ALTER TABLE ${rel(schema, table)} ALTER COLUMN ${qid(column)} SET DEFAULT ${str(p(fact, "expr"))}`,
        },
      ];
    },
    drop: (fact) => {
      const { schema, table, column } = columnRef(fact);
      return { sql: `ALTER TABLE ${rel(schema, table)} ALTER COLUMN ${qid(column)} DROP DEFAULT` };
    },
    attributes: {
      expr: {
        alter: (fact, _from, to) => {
          const { schema, table, column } = columnRef(fact);
          return {
            sql: `ALTER TABLE ${rel(schema, table)} ALTER COLUMN ${qid(column)} SET DEFAULT ${str(to)}`,
          };
        },
      },
    },
  },

  procedure: {
    weight: 8,
    create: (fact) => [
      {
        sql: str(p(fact, "def")),
        consumes: [{ kind: "role", name: str(p(fact, "owner")) }],
      },
    ],
    drop: (fact) => {
      const id = fact.id as { schema: string; name: string; args: string[] };
      const keyword = str(p(fact, "routineKind")) === "p" ? "PROCEDURE" : "FUNCTION";
      return { sql: `DROP ${keyword} ${routineSig(id)}` };
    },
    attributes: {
      def: { alter: (fact, _from, to) => ({ sql: str(to) }) },
      owner: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; name: string; args: string[] };
          const keyword = str(p(fact, "routineKind")) === "p" ? "PROCEDURE" : "FUNCTION";
          return {
            sql: `ALTER ${keyword} ${routineSig(id)} OWNER TO ${qid(str(to))}`,
            consumes: [{ kind: "role", name: str(to) }],
          };
        },
      },
      routineKind: "replace",
    },
  },

  constraint: {
    weight: 10,
    create: (fact) => {
      const id = fact.id as { schema: string; table: string; name: string };
      let sql = `ALTER TABLE ${rel(id.schema, id.table)} ADD CONSTRAINT ${qid(id.name)} ${str(p(fact, "def"))}`;
      if (!p(fact, "validated") && !str(p(fact, "def")).includes("NOT VALID")) {
        sql += " NOT VALID";
      }
      return [{ sql }];
    },
    drop: (fact) => {
      const id = fact.id as { schema: string; table: string; name: string };
      return { sql: `ALTER TABLE ${rel(id.schema, id.table)} DROP CONSTRAINT ${qid(id.name)}` };
    },
    attributes: {
      def: "replace",
      type: "replace",
      validated: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; table: string; name: string };
          if (!to) throw new Error("constraint cannot be de-validated in place");
          return {
            sql: `ALTER TABLE ${rel(id.schema, id.table)} VALIDATE CONSTRAINT ${qid(id.name)}`,
          };
        },
      },
    },
  },

  view: {
    weight: 12,
    create: (fact) => {
      const id = fact.id as { schema: string; name: string };
      const specs: ActionSpec[] = [
        {
          sql: `CREATE VIEW ${rel(id.schema, id.name)} AS ${str(p(fact, "def"))}`,
          consumes: [{ kind: "role", name: str(p(fact, "owner")) }],
        },
        {
          sql: `ALTER VIEW ${rel(id.schema, id.name)} OWNER TO ${qid(str(p(fact, "owner")))}`,
          consumes: [{ kind: "role", name: str(p(fact, "owner")) }],
        },
      ];
      return specs;
    },
    drop: (fact) => {
      const id = fact.id as { schema: string; name: string };
      return { sql: `DROP VIEW ${rel(id.schema, id.name)}` };
    },
    attributes: {
      def: "replace",
      owner: ownerRule((fact) => {
        const id = fact.id as { schema: string; name: string };
        return `ALTER VIEW ${rel(id.schema, id.name)}`;
      }),
    },
  },

  materializedView: {
    weight: 13,
    create: (fact) => {
      const id = fact.id as { schema: string; name: string };
      return [
        {
          sql: `CREATE MATERIALIZED VIEW ${rel(id.schema, id.name)} AS ${str(p(fact, "def"))}`,
          consumes: [{ kind: "role", name: str(p(fact, "owner")) }],
        },
      ];
    },
    drop: (fact) => {
      const id = fact.id as { schema: string; name: string };
      return { sql: `DROP MATERIALIZED VIEW ${rel(id.schema, id.name)}`, dataLoss: "destructive" };
    },
    attributes: {
      def: "replace",
      owner: ownerRule((fact) => {
        const id = fact.id as { schema: string; name: string };
        return `ALTER MATERIALIZED VIEW ${rel(id.schema, id.name)}`;
      }),
    },
  },

  index: {
    weight: 14,
    create: (fact) => [{ sql: str(p(fact, "def")) }],
    drop: (fact) => {
      const id = fact.id as { schema: string; name: string };
      return { sql: `DROP INDEX ${rel(id.schema, id.name)}` };
    },
    attributes: { def: "replace" },
  },

  trigger: {
    weight: 15,
    create: (fact) => [{ sql: str(p(fact, "def")) }],
    drop: (fact) => {
      const id = fact.id as { schema: string; table: string; name: string };
      return { sql: `DROP TRIGGER ${qid(id.name)} ON ${rel(id.schema, id.table)}` };
    },
    attributes: { def: "replace" },
  },

  policy: {
    weight: 16,
    create: (fact) => {
      const roles = (p(fact, "roles") as string[])
        .filter((r) => r !== "PUBLIC")
        .map((r): StableId => ({ kind: "role", name: r }));
      return [{ sql: policySql(fact), consumes: roles }];
    },
    drop: (fact) => {
      const id = fact.id as { schema: string; table: string; name: string };
      return { sql: `DROP POLICY ${qid(id.name)} ON ${rel(id.schema, id.table)}` };
    },
    attributes: {
      usingExpr: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; table: string; name: string };
          return {
            sql: `ALTER POLICY ${qid(id.name)} ON ${rel(id.schema, id.table)} USING (${str(to)})`,
          };
        },
      },
      checkExpr: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; table: string; name: string };
          return {
            sql: `ALTER POLICY ${qid(id.name)} ON ${rel(id.schema, id.table)} WITH CHECK (${str(to)})`,
          };
        },
      },
      roles: {
        alter: (fact, _from, to) => {
          const id = fact.id as { schema: string; table: string; name: string };
          const roles = (to as string[]).map((r) => (r === "PUBLIC" ? "PUBLIC" : qid(r)));
          return {
            sql: `ALTER POLICY ${qid(id.name)} ON ${rel(id.schema, id.table)} TO ${roles.join(", ")}`,
          };
        },
      },
      cmd: "replace",
      permissive: "replace",
    },
  },

  comment: {
    weight: 20,
    create: (fact) => {
      const target = (fact.id as { target: StableId }).target;
      return [{ sql: `COMMENT ON ${commentTarget(target)} IS ${lit(str(p(fact, "text")))}` }];
    },
    drop: (fact) => {
      const target = (fact.id as { target: StableId }).target;
      return { sql: `COMMENT ON ${commentTarget(target)} IS NULL` };
    },
    attributes: {
      text: {
        alter: (fact, _from, to) => {
          const target = (fact.id as { target: StableId }).target;
          return { sql: `COMMENT ON ${commentTarget(target)} IS ${lit(str(to))}` };
        },
      },
    },
  },

  acl: {
    weight: 21,
    create: (fact) => grantActions(fact, "grant"),
    drop: (fact) => {
      const id = fact.id as { kind: "acl"; target: StableId; grantee: string };
      const grantee = id.grantee === "PUBLIC" ? "PUBLIC" : qid(id.grantee);
      return {
        sql: `REVOKE ALL ON ${grantTarget(id.target)} FROM ${grantee}`,
        ...(id.grantee === "PUBLIC"
          ? {}
          : { consumes: [{ kind: "role", name: id.grantee } as StableId] }),
      };
    },
    attributes: {
      privileges: "replace",
      grantable: "replace",
    },
  },
};

export function rulesFor(kind: string): KindRules {
  const rules = RULES[kind];
  if (!rules) {
    throw new Error(
      `rule table: no rules for kind '${kind}' — extend the rule vocabulary (guardrail 3)`,
    );
  }
  return rules;
}
