/**
 * Declarative-export fidelity for IDENTITY columns whose implicit backing
 * sequence has a NON-DEFAULT name.
 *
 * An identity column (`GENERATED … AS IDENTITY`) owns an implicit sequence.
 * PostgreSQL names it `<table>_<column>_seq` by default, but the name can
 * diverge — the sequence was renamed, or created via `SEQUENCE NAME`. pg-delta
 * extracts the real name, but if the export renders a bare `AS IDENTITY` with
 * no `SEQUENCE NAME` clause, the reload lets PostgreSQL re-derive the default
 * name — which no longer matches the source → a spurious `ALTER SEQUENCE …
 * RENAME` on the next diff (dogfooded on `public.custom_config_gotrue.id`,
 * whose sequence is `auth_config_id_seq`).
 *
 * The fix emits `SEQUENCE NAME "<schema>"."<name>"` inside the identity options
 * parens when the name differs from the `<table>_<column>_seq` default, and
 * keeps default-named columns bare so ordinary exports stay minimal.
 *
 * Docker required.
 */
import { describe, expect, test } from "bun:test";
import { extract } from "../src/extract/extract.ts";
import { exportSqlFiles } from "../src/frontends/export-sql-files.ts";
import { loadSqlFiles } from "../src/frontends/load-sql-files.ts";
import { sharedCluster } from "./containers.ts";

function forLoad(files: { name: string; sql: string }[]) {
  // roles are cluster-global and already present in the shared cluster; drop
  // the CREATE ROLE file exactly as export-fidelity.test.ts does.
  return files.filter((f) => !/cluster[_/]roles/.test(f.name));
}

describe("export: identity backing-sequence name fidelity", () => {
  test("renamed identity sequence round-trips and emits SEQUENCE NAME", async () => {
    const cluster = await sharedCluster();
    const src = await cluster.createDb("idseq_named_src");
    const shadow = await cluster.createDb("idseq_named_shadow");
    try {
      await src.pool.query(`
        CREATE SCHEMA g;
        CREATE TABLE g.t (id integer GENERATED BY DEFAULT AS IDENTITY, x integer);
        ALTER SEQUENCE g.t_id_seq RENAME TO renamed_seq;
      `);
      const fb = (await extract(src.pool)).factBase;

      const files = forLoad(exportSqlFiles(fb));
      expect(files.some((f) => f.name.includes("/sequences/"))).toBe(false);
      const all = files.map((f) => f.sql).join("\n");
      // the renamed sequence name must be reproduced explicitly
      expect(all.toLowerCase()).toContain("sequence name");
      expect(all).toContain("renamed_seq");

      const loaded = await loadSqlFiles(files, shadow.pool);
      // rootHash folds the identity payload (incl. the backing sequence
      // {schema,name}); equality here == zero residual actions on re-diff.
      expect(loaded.factBase.rootHash).toBe(fb.rootHash);
    } finally {
      await Promise.all([src.drop(), shadow.drop()]);
    }
  }, 120_000);

  test("default-named identity sequence stays bare (no SEQUENCE NAME) and round-trips", async () => {
    const cluster = await sharedCluster();
    const src = await cluster.createDb("idseq_default_src");
    const shadow = await cluster.createDb("idseq_default_shadow");
    try {
      await src.pool.query(`
        CREATE SCHEMA h;
        CREATE TABLE h.t2 (id integer GENERATED ALWAYS AS IDENTITY, x integer);
      `);
      const fb = (await extract(src.pool)).factBase;

      const files = forLoad(exportSqlFiles(fb));
      expect(files.some((f) => f.name.includes("/sequences/"))).toBe(false);
      const all = files.map((f) => f.sql).join("\n");
      // default `<table>_<column>_seq` name → export stays minimal
      expect(all.toLowerCase()).not.toContain("sequence name");

      const loaded = await loadSqlFiles(files, shadow.pool);
      expect(loaded.factBase.rootHash).toBe(fb.rootHash);
    } finally {
      await Promise.all([src.drop(), shadow.drop()]);
    }
  }, 120_000);
});
