/**
 * Opt-in bounded-parallel extraction (`ExtractOptions.concurrency`).
 *
 * The contract under test is EQUIVALENCE, not speed: N catalog-query streams
 * sharing the coordinator's `pg_export_snapshot()` must reproduce the serial
 * extraction byte-for-byte — same FactBase rootHash, same fact order, same edge
 * order, same diagnostics order — because the scheduler slots per-family results
 * by family index and merges in the fixed call order, never completion order.
 *
 * Everything else here is about not hurting anyone: never queue on an exhausted
 * pool (that would deadlock, since the coordinator holds a client while asking
 * for more), degrade silently to serial when the snapshot cannot be shared, and
 * leak no client / open transaction on any error path.
 */
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import pg from "pg";
import type { Diagnostic } from "../src/core/diagnostic.ts";
import type { DependencyEdge, Fact } from "../src/core/fact.ts";
import {
  extract,
  ExtractionTimeoutError,
  type ExtractResult,
} from "../src/extract/extract.ts";
import { createTestDb, type TestDb } from "./containers.ts";

/**
 * A schema broad enough that every extractor family contributes something and
 * the families that interact do so: identity + GENERATED columns (the
 * `defaultFactIds` / shadow-edge interplay in dependencies.ts, which is the ONLY
 * cross-family read in the whole extractor), FKs, views + matviews, routines,
 * triggers, RLS policies, enums, domains, composite types, collations, rules,
 * sequences, comments, and ACL grants. `pgcrypto` covers extension membership
 * provenance cheaply.
 */
function fixtureSql(): string {
  return `
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    CREATE ROLE app_reader NOLOGIN;
    CREATE ROLE app_writer NOLOGIN;
    GRANT app_reader TO app_writer;

    CREATE SCHEMA app;
    COMMENT ON SCHEMA app IS 'application objects';

    CREATE TYPE app.status AS ENUM ('draft', 'live', 'archived');
    CREATE TYPE app.money_pair AS (low numeric, high numeric);
    CREATE DOMAIN app.positive_int AS integer CHECK (VALUE > 0);
    CREATE COLLATION app.ci (provider = icu, locale = 'und-u-ks-level2', deterministic = false);

    CREATE SEQUENCE app.legacy_counter START 100 INCREMENT 5;

    CREATE TABLE app.tenants (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      slug text NOT NULL UNIQUE,
      created_at timestamptz NOT NULL DEFAULT now()
    );
    COMMENT ON TABLE app.tenants IS 'tenant registry';
    COMMENT ON COLUMN app.tenants.slug IS 'url-safe key';

    CREATE TABLE app.documents (
      id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      tenant_id integer NOT NULL REFERENCES app.tenants (id) ON DELETE CASCADE,
      title text NOT NULL,
      -- GENERATED column: no \`default\` fact exists, so the pg_depend shadow edge
      -- onto the column is the only carrier (dependencies.ts P2)
      title_upper text GENERATED ALWAYS AS (upper(title)) STORED,
      body text DEFAULT ''::text,
      state app.status NOT NULL DEFAULT 'draft',
      weight app.positive_int DEFAULT 1,
      span app.money_pair,
      legacy integer DEFAULT nextval('app.legacy_counter'),
      CONSTRAINT documents_title_not_blank CHECK (length(title) > 0)
    );
    CREATE INDEX documents_tenant_idx ON app.documents (tenant_id);
    CREATE INDEX documents_state_live_idx ON app.documents (tenant_id)
      WHERE state = 'live';

    CREATE TABLE app.events (
      id integer GENERATED BY DEFAULT AS IDENTITY,
      document_id bigint REFERENCES app.documents (id),
      at timestamptz NOT NULL DEFAULT now(),
      -- a partitioned table's PK must cover the partition key
      PRIMARY KEY (id, at)
    ) PARTITION BY RANGE (at);
    CREATE TABLE app.events_2024 PARTITION OF app.events
      FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

    CREATE VIEW app.live_documents AS
      SELECT d.id, d.title, d.title_upper, t.slug
      FROM app.documents d JOIN app.tenants t ON t.id = d.tenant_id
      WHERE d.state = 'live';
    CREATE MATERIALIZED VIEW app.document_counts AS
      SELECT tenant_id, count(*) AS n FROM app.documents GROUP BY tenant_id;
    CREATE UNIQUE INDEX document_counts_tenant_idx
      ON app.document_counts (tenant_id);

    CREATE FUNCTION app.slugify(input text) RETURNS text
      LANGUAGE sql IMMUTABLE AS $$ SELECT lower(regexp_replace(input, '\\W+', '-', 'g')) $$;
    CREATE FUNCTION app.touch() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN NEW.at := now(); RETURN NEW; END $$;
    CREATE PROCEDURE app.noop() LANGUAGE plpgsql AS $$ BEGIN END $$;
    CREATE AGGREGATE app.sum_positive (app.positive_int) (
      SFUNC = int4pl, STYPE = integer, INITCOND = '0'
    );

    CREATE TRIGGER events_touch BEFORE INSERT ON app.events_2024
      FOR EACH ROW EXECUTE FUNCTION app.touch();

    ALTER TABLE app.documents ENABLE ROW LEVEL SECURITY;
    CREATE POLICY documents_read ON app.documents FOR SELECT
      TO app_reader USING (state = 'live');
    CREATE POLICY documents_write ON app.documents FOR INSERT
      TO app_writer WITH CHECK (length(title) > 0);

    CREATE TABLE app.audit_sink (payload text);
    CREATE RULE audit_no_delete AS ON DELETE TO app.audit_sink DO INSTEAD NOTHING;

    GRANT USAGE ON SCHEMA app TO app_reader;
    GRANT SELECT ON app.documents TO app_reader;
    GRANT SELECT, INSERT, UPDATE ON app.documents TO app_writer;
    GRANT USAGE, SELECT ON SEQUENCE app.legacy_counter TO app_writer;
    GRANT EXECUTE ON FUNCTION app.slugify(text) TO app_reader;
  `;
}

/** The comparison surface: everything a caller can observe about an extraction,
 *  in ORDER. Fact / edge / diagnostic ordering is exactly what a completion-order
 *  merge bug would scramble, so nothing here is sorted before comparing. */
interface Observed {
  rootHash: string;
  pgVersion: string;
  facts: Fact[];
  edges: readonly DependencyEdge[];
  factBaseDiagnostics: Diagnostic[];
  diagnostics: Diagnostic[];
}

function observe(result: ExtractResult): Observed {
  return {
    rootHash: result.factBase.rootHash,
    pgVersion: result.pgVersion,
    facts: result.factBase.facts(),
    edges: result.factBase.edges,
    factBaseDiagnostics: result.factBase.diagnostics,
    diagnostics: result.diagnostics,
  };
}

/** The rejection value of `promise`, awaited (so nothing is left dangling) and
 *  asserted to have happened at all. */
async function rejection(promise: Promise<unknown>): Promise<unknown> {
  try {
    await promise;
  } catch (error) {
    return error;
  }
  throw new Error("expected the promise to reject, but it resolved");
}

/** Every checked-out client came back, and the pool never grew past its cap. */
function expectPoolDrained(pool: pg.Pool, max: number): void {
  expect(pool.waitingCount).toBe(0);
  expect(pool.totalCount).toBeLessThanOrEqual(max);
  expect(pool.idleCount).toBe(pool.totalCount);
}

// ── round-trip / session-state instrumentation ──────────────────────────────

/**
 * Fragments that only ever appear in SESSION SETUP sql. Each matching
 * `client.query()` CALL is one network round trip, however many statements it
 * batches — which is exactly the quantity these tests pin.
 */
const SETUP_MARKERS = [
  "BEGIN ISOLATION LEVEL",
  "SET LOCAL search_path",
  "SET LOCAL statement_timeout",
  "SET TRANSACTION SNAPSHOT",
  "SET LOCAL jit",
  "set_config('jit'",
  "pg_export_snapshot()",
  "current_setting('server_version')",
];

const isSetupCall = (sql: string): boolean =>
  SETUP_MARKERS.some((marker) => sql.includes(marker));

/**
 * Total `client.query()` calls across every client the pool hands out. One call
 * is one network ROUND TRIP, however many statements it batches — which is the
 * quantity that decides extraction wall time on a remote database, where each
 * one costs a full RTT before the next can start.
 */
function countRoundTrips(pool: pg.Pool): () => number {
  let calls = 0;
  const patched = new Map<pg.PoolClient, unknown>();
  const onAcquire = (client: pg.PoolClient): void => {
    if (patched.has(client)) return;
    const realQuery = client.query.bind(client);
    patched.set(client, (client as { query: unknown }).query);
    // oxlint-disable-next-line no-explicit-any -- passthrough test double
    (client as any).query = (...args: any[]) => {
      if (typeof args[0] === "string") calls++;
      // oxlint-disable-next-line no-explicit-any -- passthrough test double
      return (realQuery as any)(...args);
    };
  };
  pool.on("acquire", onAcquire);
  return () => {
    pool.off("acquire", onAcquire);
    for (const [client, query] of patched) {
      (client as { query: unknown }).query = query;
    }
    return calls;
  };
}

/** The GUCs and transaction characteristics that define the canonical extraction
 *  session. Read in ONE round trip, off the connection actually extracting. */
const SESSION_STATE_SQL = `SELECT current_setting('search_path') AS search_path,
         current_setting('statement_timeout') AS statement_timeout,
         current_setting('jit') AS jit,
         current_setting('transaction_isolation') AS isolation,
         current_setting('transaction_read_only') AS read_only`;

interface ClientTrace {
  /** `client.query()` calls that carried session setup — i.e. setup round trips. */
  setupCalls: number;
  /** Session state as it stood when this connection ran its first CATALOG query,
   *  i.e. the state the extraction actually reads the catalog in. */
  state?: Record<string, string>;
}

/**
 * Observe every checked-out client to report (a) how many setup
 * round trips it paid and (b) the session state it was left in — captured lazily,
 * immediately before its first non-setup query, which is the only moment where
 * "setup finished" is observable from outside without changing the ordering that
 * `SET TRANSACTION SNAPSHOT` depends on.
 */
function traceSetup(pool: pg.Pool): () => ClientTrace[] {
  const traces: ClientTrace[] = [];
  const patched = new Map<pg.PoolClient, unknown>();
  const onAcquire = (client: pg.PoolClient): void => {
    if (patched.has(client)) return;
    const trace: ClientTrace = { setupCalls: 0 };
    traces.push(trace);
    const realQuery = client.query.bind(client);
    patched.set(client, (client as { query: unknown }).query);
    let capturing = false;
    // oxlint-disable-next-line no-explicit-any -- passthrough test double
    (client as any).query = async (...args: any[]) => {
      const sql = typeof args[0] === "string" ? args[0] : "";
      if (isSetupCall(sql)) {
        trace.setupCalls++;
      } else if (trace.state === undefined && !capturing && sql !== "") {
        capturing = true;
        // oxlint-disable-next-line no-explicit-any -- passthrough test double
        const probe = await (realQuery as any)(SESSION_STATE_SQL);
        trace.state = probe.rows[0] as Record<string, string>;
        capturing = false;
      }
      // oxlint-disable-next-line no-explicit-any -- passthrough test double
      return (realQuery as any)(...args);
    };
  };
  pool.on("acquire", onAcquire);
  return () => {
    pool.off("acquire", onAcquire);
    for (const [client, query] of patched) {
      (client as { query: unknown }).query = query;
    }
    return traces;
  };
}

let db: TestDb;

beforeAll(async () => {
  db = await createTestDb("parallel-extract");
  await db.pool.query(fixtureSql());
}, 180_000);

afterAll(async () => {
  await db.pool.query(`DROP OWNED BY app_writer`).catch(() => {});
  await db.drop();
  await db.cluster.adminPool
    .query(`DROP ROLE IF EXISTS app_writer, app_reader`)
    .catch(() => {});
});

describe("extract: bounded-parallel extraction", () => {
  test("concurrency 2, 4 and 5 reproduce the serial extraction exactly", async () => {
    const serial = observe(await extract(db.pool));
    // sanity: the fixture really does exercise the whole extractor
    expect(serial.facts.length).toBeGreaterThan(100);
    expect(serial.edges.length).toBeGreaterThan(100);

    // 5 saturates the pool (coordinator + 4 workers), so the tail BATCH jobs —
    // each of which fills several family slots at once — land on different
    // streams than the heavy single-family jobs. That is the shape a
    // completion-order merge bug would show up in.
    for (const concurrency of [2, 4, 5]) {
      const parallel = observe(await extract(db.pool, { concurrency }));
      expect(parallel.rootHash).toBe(serial.rootHash);
      expect(parallel.pgVersion).toBe(serial.pgVersion);
      expect(parallel.facts).toEqual(serial.facts);
      expect(parallel.edges).toEqual(serial.edges);
      expect(parallel.factBaseDiagnostics).toEqual(serial.factBaseDiagnostics);
      expect(parallel.diagnostics).toEqual(serial.diagnostics);
    }
  }, 180_000);

  test("concurrency 4 actually opens extra streams on the pool", async () => {
    // The behavioral claim behind the option: more than one catalog-query stream
    // is genuinely in flight, so the pool has to hand out more than the single
    // coordinator client. A serial extraction can never make this true.
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    let peakTotal = 0;
    const sampler = setInterval(() => {
      peakTotal = Math.max(peakTotal, pool.totalCount);
    }, 2);
    try {
      await extract(pool, { concurrency: 4 });
    } finally {
      clearInterval(sampler);
    }
    expect(peakTotal).toBeGreaterThanOrEqual(2);
    expect(pool.totalCount).toBe(4);
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);

  test("concurrency above the pool cap completes without deadlocking", async () => {
    // `pg.Pool.connect()` QUEUES when the pool is exhausted, and the coordinator
    // holds one client for the whole extraction — asking for more clients than
    // the pool can give would wait forever. Clamping to the pool's own max is
    // what makes this terminate.
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    const serial = observe(await extract(db.pool));
    const result = observe(await extract(pool, { concurrency: 8 }));
    expect(result.rootHash).toBe(serial.rootHash);
    expect(result.facts).toEqual(serial.facts);
    expect(result.edges).toEqual(serial.edges);
    expect(result.diagnostics).toEqual(serial.diagnostics);
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);

  test("a max:1 pool degrades to serial instead of hanging", async () => {
    const pool = new pg.Pool({ connectionString: db.uri, max: 1 });
    pool.on("error", () => {});
    const serial = observe(await extract(db.pool));
    const result = observe(await extract(pool, { concurrency: 4 }));
    expect(result.rootHash).toBe(serial.rootHash);
    expect(result.facts).toEqual(serial.facts);
    expect(result.edges).toEqual(serial.edges);
    // silent degradation: no new diagnostic tells the caller it went serial
    expect(result.diagnostics).toEqual(serial.diagnostics);
    expectPoolDrained(pool, 1);
    await pool.end();
  }, 180_000);

  test("a failing family rejects and releases every client", async () => {
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    // Poison ONE family's catalog query (policies) on whichever stream happens
    // to run it. The rest of the streams are mid-query when it blows up, so this
    // is the "worker fails while others are in flight" cleanup path.
    const boom = new Error("poisoned pg_policy read");
    pool.on("acquire", (client) => {
      const realQuery = client.query.bind(client);
      // oxlint-disable-next-line no-explicit-any -- passthrough test double
      (client as any).query = (...args: any[]) => {
        if (typeof args[0] === "string" && args[0].includes("pg_policy")) {
          return Promise.reject(boom);
        }
        // oxlint-disable-next-line no-explicit-any -- passthrough test double
        return (realQuery as any)(...args);
      };
    });

    expect(await rejection(extract(pool, { concurrency: 4 }))).toBe(boom);
    expectPoolDrained(pool, 5);
    // and the released clients are genuinely usable — no transaction left open
    const probe = await pool.connect();
    expect((await probe.query("SELECT 1 AS ok")).rows[0]).toEqual({ ok: 1 });
    probe.release();
    await pool.end();
  }, 180_000);

  test("ExtractionTimeoutError still surfaces from a worker stream", async () => {
    let err: unknown;
    try {
      await extract(db.pool, { concurrency: 4, statementTimeoutMs: 1 });
    } catch (e) {
      err = e;
    }
    expect(err).toBeInstanceOf(ExtractionTimeoutError);
    const timeout = err as ExtractionTimeoutError;
    expect(timeout.timeoutMs).toBe(1);
    expect(timeout.queryLabel.length).toBeGreaterThan(0);
    expectPoolDrained(db.pool, 5);
  }, 180_000);

  test("concurrency 1 and undefined are the same path", async () => {
    const serial = observe(await extract(db.pool));
    const one = observe(await extract(db.pool, { concurrency: 1 }));
    expect(one.rootHash).toBe(serial.rootHash);
    expect(one.facts).toEqual(serial.facts);
    expect(one.edges).toEqual(serial.edges);
    expect(one.diagnostics).toEqual(serial.diagnostics);
    expectPoolDrained(db.pool, 5);
  }, 180_000);

  test("a nonsense concurrency is rejected loudly", async () => {
    for (const bad of [0, -1, 2.5, Number.NaN, Number.POSITIVE_INFINITY]) {
      const error = await rejection(extract(db.pool, { concurrency: bad }));
      expect((error as Error).message).toMatch(/concurrency/i);
    }
    expectPoolDrained(db.pool, 5);
  }, 60_000);

  test("a refused snapshot export falls back to serial, silently", async () => {
    // What a hot standby or a restrictive pooler does. The export rides in the
    // coordinator's OPENING batch, so its failure aborts that transaction — the
    // fallback has to roll back, re-open, and hand back the clients it had already
    // reserved for workers (releasing a client twice is an error in node-pg, so
    // this also pins that the reservation has exactly one owner).
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    const patched = new WeakSet<pg.PoolClient>();
    const refuseSnapshot = (client: pg.PoolClient): void => {
      if (patched.has(client)) return;
      patched.add(client);
      const realQuery = client.query.bind(client);
      // oxlint-disable-next-line no-explicit-any -- passthrough test double
      (client as any).query = (...args: any[]) => {
        if (
          typeof args[0] === "string" &&
          args[0].includes("pg_export_snapshot()")
        ) {
          return Promise.reject(
            Object.assign(
              new Error("cannot export a snapshot during recovery"),
              {
                code: "55000",
              },
            ),
          );
        }
        // oxlint-disable-next-line no-explicit-any -- passthrough test double
        return (realQuery as any)(...args);
      };
    };

    pool.on("acquire", refuseSnapshot);
    const serial = observe(await extract(db.pool));
    const result = await (async () => {
      try {
        return observe(await extract(pool, { concurrency: 4 }));
      } finally {
        pool.off("acquire", refuseSnapshot);
      }
    })();
    expect(result.rootHash).toBe(serial.rootHash);
    expect(result.facts).toEqual(serial.facts);
    expect(result.edges).toEqual(serial.edges);
    // silent: falling back must not add a diagnostic
    expect(result.diagnostics).toEqual(serial.diagnostics);
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);

  test("fewer spare clients than requested still extracts correctly", async () => {
    // spareCapacity() trims the worker count when a SHARED pool is already busy.
    // The stream count then has to follow the workers we actually got — asking
    // the scheduler for more streams than there are connections would hand a job
    // an undefined query runner.
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    const serial = observe(await extract(db.pool));
    // hog 3 of 5, leaving room for the coordinator + exactly one worker
    const hogs = [
      await pool.connect(),
      await pool.connect(),
      await pool.connect(),
    ];
    try {
      const result = observe(await extract(pool, { concurrency: 4 }));
      expect(result.rootHash).toBe(serial.rootHash);
      expect(result.facts).toEqual(serial.facts);
      expect(result.edges).toEqual(serial.edges);
      expect(result.diagnostics).toEqual(serial.diagnostics);
    } finally {
      for (const hog of hogs) hog.release();
    }
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);
});

/**
 * Setup cost is measured in ROUND TRIPS, not statements — that is the quantity
 * that hurts on a remote database, where each one costs a full RTT before any
 * catalog work can start.
 *
 * Two is the floor for the coordinator, not one: the JIT-off statement's form
 * depends on the server major version, and the >= 15 form calls
 * `has_parameter_privilege()`, which does not exist on 14 — so it cannot ride in
 * the same batch as the probe that reveals the version without risking a
 * mid-batch error, which would abort the whole transaction. Workers do get to one,
 * because by then the version is known.
 */
describe("extract: session setup cost", () => {
  test("serial setup is 2 batched round trips", async () => {
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    const traces = traceSetup(pool);
    await extract(pool);
    const clients = traces();
    expect(clients).toHaveLength(1);
    // (1) BEGIN + search_path + version probe, batched, then (2) JIT-off
    expect(clients[0]!.setupCalls).toBe(2);
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);

  test("serial setup stays 2 round trips with a statement budget", async () => {
    // the budget adds a SET LOCAL statement, but not a round trip — it batches
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    const traces = traceSetup(pool);
    await extract(pool, { statementTimeoutMs: 60_000 });
    expect(traces()[0]!.setupCalls).toBe(2);
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);

  test("parallel setup is 2 round trips for the coordinator and 1 per worker", async () => {
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    const traces = traceSetup(pool);
    await extract(pool, { concurrency: 4 });
    const clients = traces();
    expect(clients).toHaveLength(4);
    // Coordinator pays the same 2 as the serial path — pg_export_snapshot() rides
    // in the opening batch, so sharing the snapshot costs no extra round trip.
    expect(clients[0]!.setupCalls).toBe(2);
    // Every worker is a SINGLE batch: BEGIN + SET TRANSACTION SNAPSHOT +
    // search_path + JIT-off. Not one round trip per statement, and not serialized
    // behind each other.
    for (const worker of clients.slice(1)) {
      expect(worker.setupCalls).toBe(1);
    }
    // 2 + 3x1 — the whole setup prefix, whatever the stream count
    expect(clients.reduce((n, c) => n + c.setupCalls, 0)).toBe(5);
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);

  test("workers extract in exactly the coordinator's session state", async () => {
    const serialPool = new pg.Pool({ connectionString: db.uri, max: 5 });
    serialPool.on("error", () => {});
    const serialTraces = traceSetup(serialPool);
    await extract(serialPool, { statementTimeoutMs: 60_000 });
    const serialState = serialTraces()[0]!.state;
    expect(serialState).toEqual({
      search_path: "pg_catalog",
      statement_timeout: "1min",
      jit: "off",
      isolation: "repeatable read",
      read_only: "on",
    });
    await serialPool.end();

    const parallelPool = new pg.Pool({ connectionString: db.uri, max: 5 });
    parallelPool.on("error", () => {});
    const parallelTraces = traceSetup(parallelPool);
    await extract(parallelPool, { concurrency: 4, statementTimeoutMs: 60_000 });
    const clients = parallelTraces();
    expect(clients).toHaveLength(4);
    // coordinator AND every worker land in the byte-identical session the serial
    // path uses — batching the setup changed the round trips, not the state
    for (const client of clients) {
      expect(client.state).toEqual(serialState);
    }
    await parallelPool.end();
  }, 180_000);
});

/**
 * The whole catalog scan, counted in ROUND TRIPS rather than statements.
 *
 * The cheap "tail" families (roles, schemas, tables, sequences, views, domains,
 * types, collations, event triggers, rules, publications, inheritance) cost
 * almost nothing server-side — their price is pure RTT — so their statements are
 * packed into a few multi-statement round trips instead of one each, while the
 * measured server/transfer-heavy families keep their own (see
 * CATALOG_BATCH_GROUPS in src/extract/extract.ts).
 *
 * The assertion is a BUDGET, not an exact count: it must fail loudly if a future
 * change reintroduces a per-family round trip, without churning every time a
 * family legitimately gains or loses a statement or a PG version adds a probe.
 */
describe("extract: catalog round-trip budget", () => {
  test("a serial extraction fits the batched round-trip budget", async () => {
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    const roundTrips = countRoundTrips(pool);
    await extract(pool);
    // measured 23 on postgres:17-alpine (38 before the tail was batched):
    // 1 opening batch + 1 JIT-off + 7 heavy families + 5 foreign + 2
    // subscriptions + 1 security-label probe + 3 tail batches + 1 pg_depend
    // resolver + 1 unmodeled-kind scan + COMMIT.
    expect(roundTrips()).toBeLessThanOrEqual(24);
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);
});
