-- state A: identity column whose backing sequence carries a grant
DO $$ BEGIN CREATE ROLE corpus_idseq_drop_r NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE SCHEMA test_schema;
CREATE TABLE test_schema.t_ident (id bigint GENERATED BY DEFAULT AS IDENTITY, v int);
GRANT USAGE, SELECT ON SEQUENCE test_schema.t_ident_id_seq TO corpus_idseq_drop_r;
